### ISSUE TITLE
Add support for Two-Factor-Authentication protected accounts.

### ISSUE THREAD

**Issue by rdvl97** [EionRobb/purple-discord#1]
At the moment if you try to login to your account and it has 2FA enabled, the connection closes with a Bad Username/Password error.

**Comment by EionRobb** [comment]
Whoops, I hadn't factored 2FA in (pun intended!)

I'll set that up on my account and see what's needed now :)

**Comment by EionRobb** [comment]
That should do the trick.  Give it a go and let me know how you get on :)

**Comment by rdvl97** [comment]
Is this change reflected in the binary on your site?  im not on a system i can compile on at the moment.

**Comment by EionRobb** [comment]
Yep, updated the dll on my site https://eion.robbmob.com/libdiscord.dll

**Comment by rdvl97** [comment]
is a new prompt supposed to come up when logging in?
the plugin's behaviour seems totally unchanged

**Comment by rdvl97** [comment]
oh wait, nevermind.  the dll didnt properly overwrite when downloading cause it was still being used by pidgin.  one sec

**Comment by EionRobb** [comment]
Yeah, unfortunately Pidgin can't update plugins while it's running.
![image](https://cloud.githubusercontent.com/assets/1063865/25115772/7d31916a-245c-11e7-9cde-2b991f817688.png)
is what the new prompt looks like

**Comment by rdvl97** [comment]
works perfectly!  Thanks man.  you're awesome :smile:

**Comment by EionRobb** [comment]
w00t!

Glad it's working :)

**Comment by thundergreen** [comment]
How does it work for purple discord? Same issue here
