### ISSUE TITLE
Crashes when gets message from "conference"

### ISSUE THREAD

**Issue by Eoksni** [EionRobb/purple-discord#107]
Using pidgin as "host" for plugin on GNOME Fedora 26.

Here I'm talking not about chat channels within servers (with # sign in their title). Instead, it is about "conferences" (similar thing is called conference in skype, I have no idea how it is called in discord) - those things that happen when you send a personal message to someone, and then add other people to the same chat.

So, when you get an unread message from such conference, pidgin crashes.
If you already have unread messages from such conference when you start pidgin, it crashes immediately after connecting.

**Comment by EionRobb** [comment]
Can you get a backtrace of the crash? 

Also, what revision from git are you using?

**Comment by bobbybee** [comment]
This was recently fixed (last night, I think? Hehe). For the time being,
please build from the source on Github as opposed to using the
(outdated) package in Fedora's repositories.

Alternatively, pester the Fedora mantainer to update the package ;)

**Comment by Eoksni** [comment]
Awesome to hear that!
Yes, I'm using version from repository, its
```
Name         : purple-discord
Version      : 0
Release      : 7.20170608git5263aff.fc26
```
I will try the github version later today and report if the issue is gone, thank you for the lightning-fast response!

**Comment by bobbybee** [comment]
If only Eion could be that lightning fast with code reviews... :P

If you're going to use group DMs, watch out for
https://github.com/EionRobb/purple-discord/issues/105 which will get
annoying quickly. I'm working on a fix at the moment.

**Comment by Eoksni** [comment]
Alright, using 26af6eccca814261df0bbfdcc2ba516bcf375937
I now have a list of DM groups (which indeed gets duplicated as you mentioned), but it seems the problem persists :(
If I write to group DM, pidgin crashes (but still sends the message to the server),
if I receive message from group DM, pidgin crashes, but marks message as read, so after restart it is not crashed until new message comes in.

I'm still using pidgin and pidgin-discord from repo, not from sources.

**Comment by bobbybee** [comment]
Please run `$ gdb pidgin` and, after these crashes, type bt to get a backtrace. Paste that here.

**Comment by EionRobb** [comment]
https://developer.pidgin.im/wiki/GetABacktrace has helpful pointers about getting a backtrace too

**Comment by bobbybee** [comment]
I think I fixed this; waiting for Eion to merge.

**Comment by Eoksni** [comment]
Sorry for the delay. I suspect I'm late already, but I'll still post a backtrace just in case.
Here it is
```
(gdb) bt
#0  0x00007f47067319c0 in g_int64_hash () at /lib64/libglib-2.0.so.0
#1  0x00007f4706730d94 in g_hash_table_lookup () at /lib64/libglib-2.0.so.0
#2  0x00007f46f21aa0c7 in discord_process_message (da=da@entry=0x100f80af0, data=data@entry=0x100fdcd20)
    at libdiscord.c:1692
#3  0x00007f46f21af40a in discord_got_history_of_room (da=0x100f80af0, node=<optimized out>, user_data=0x101185e40)
    at libdiscord.c:3613
#4  0x00007f46f21a9099 in discord_response_callback (http_conn=<optimized out>, user_data=0x101326040, url_text=<optimized out>, len=<optimized out>, error_message=0x0) at libdiscord.c:1015
#5  0x00007f47085489a5 in url_fetch_recv_cb (url_data=0x10136d880, source=<optimized out>, cond=<optimized out>)
    at util.c:4002
#6  0x0000000100071a7e in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x1011084f0)
    at gtkeventloop.c:73
#7  0x00007f4706742247 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#8  0x00007f47067425e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#9  0x00007f4706742902 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#10 0x00007f470a2550f7 in gtk_main () at /lib64/libgtk-x11-2.0.so.0
#11 0x0000000100038115 in main (argc=<optimized out>, argv=<optimized out>) at gtkmain.c:939
```
Here's how I got it
```
$ sudo dnf debuginfo-install pidgin-2.12.0-2.fc26.x86_64
$ sudo dnf debuginfo-install glibc-2.25-7.fc26.x86_64
$ gdb pidgin
(gdb) handle SIGPIPE nostop noprint
(gdb) run
... wait few seconds, pidgin starts up, I double-click one of the group DMs, pidgin freezes ...
(gdb) bt
```

**Comment by bobbybee** [comment]
Yeah, either Eion or me (or maybe both?) fixed this sometime last night
/ this morning. Pull the latest changes; it should go away :)

**Comment by Eoksni** [comment]
Great, no crashes now, big thanks!

Using cdcc32ae9998a5d66cc2ed096f9b80ce50e14d5c
