### ISSUE TITLE
Highlighting / notifying for username mentions.

### ISSUE THREAD

**Issue by rdvl97** [EionRobb/purple-discord#11]
Not sure if this one is even really possible with pidgin, but it would certainly be useful.

**Comment by EionRobb** [comment]
It definitely is possible with the `PURPLE_MESSAGE_NICK` flag.  I just need to test that out.

**Comment by EionRobb** [comment]
https://github.com/EionRobb/purple-discord/commit/7e624c24751ab53d1d9a10d124f41aa6646b3c65 should do the trick, if you can try with the latest dll?
