### ISSUE TITLE
New Makefile Translation handling might break building

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#119]
Seems that in presence of the Italian Translation, the install process stops. I'm including the build log.

For some reason now I can't reproduce the issue.

Could this be because I use make's "-j4" parameter?
[buildlog.zip](https://github.com/EionRobb/purple-discord/files/1248118/buildlog.zip)

**Comment by EionRobb** [comment]
It is indeed the parallelism of -j4 causing a thread race. The Makefile shouldn't be outputting to a file called tmp and then renaming that into a po file as doing this simultaneously will cause multiple files to overwrite tmp

**Comment by Penaz91** [comment]
Would there be a way to make this thread-safe, or at least force make to run with only 1 job?

**Comment by EionRobb** [comment]
Yes 😎

**Comment by Penaz91** [comment]
I wasn't expecting anything less from you xD

**Comment by EionRobb** [comment]
How bow dat?

**Comment by Penaz91** [comment]
Tested and seems to be working fine, I'll close this issue for now, and eventually ask for a reopen if it stops working ;)
