### ISSUE TITLE
Improved Auto-Creation of Rooms

### ISSUE THREAD

**Issue by Chromace** [EionRobb/purple-discord#122]
Currently, the plugin places auto-created rooms in the same group as Discord contacts/buddies. This can make finding the rooms a person wishes to join rather difficult, especially if a person is using multiple servers.

As such, it would be nice if the plugin had the ability to create separate groups in the buddy list for each server that a person has. E.g. Server A has a separate group, along with Server B. A single Discord group for contacts and direct messages from groups, etc.

Possibly as an option to enable?

**Comment by EionRobb** [comment]
That's the way the setting works at the moment, eg my buddy list looks like
![image](https://user-images.githubusercontent.com/1063865/30018182-038ab4b0-91b0-11e7-9685-d91805832d3a.png)
which has the different servers and the various groups within them.

What version of the plugin are you using?

**Comment by EionRobb** [comment]
The other option is to disable the "Auto-create rooms on buddy list" setting and manually add them from the Tools->Room List menu, but probably more cumbersome

**Comment by alexolog** [comment]
The problem with auto-create is that it's an all our nothing proposition.  If a server has dozens of rooms that I am not interested in, there seems to be no way to blacklist them.

**Comment by Chromace** [comment]
I'm using the build that has everything up to and including the 2nd of September. I experimented with the auto-create tool, by removing the blist.xml file and regenerating it. It caused contacts and server rooms to be grouped into a single group under 'Discord'.

**Comment by EionRobb** [comment]
@Chromace can you provide the version number from Help->Plugin Information for the Discord plugin (about 1/3rd of the way down)

**Comment by Chromace** [comment]
0.9.2017.09.04

**Comment by Chromace** [comment]
Perhaps the addition of Discord Guild Categories (https://support.discordapp.com/hc/en-us/articles/115001580171-Channel-Categories-101) might be what's causing this problem? It only cropped up a little while later. They show up as regular rooms which can be clicked on and joined as regular text channels.

They turn up in the Discord group when the auto-generation feature is enabled. It's possible that they may also be responsible for the occasional room duplicates which are generated on startup.

![channel categories](https://user-images.githubusercontent.com/16624211/31106880-54641b92-a83a-11e7-8a03-77189687e293.png)

**Comment by Chromace** [comment]
Something interesting to note is that the separate server groups _are_ indeed created, but they are empty. Instead, all the rooms from the different servers are directed into the Discord group, along with all the contacts.

**Comment by bobbybee** [comment]
That _is_ strange :/

**Comment by bobbybee** [comment]
I don't believe this applies to the current master. Please reopen if you're still having troubles. Thanks!
