### ISSUE TITLE
Utilize Travis for posting releases to GitHub's Releases page

### ISSUE THREAD

**Issue by aph3rson** [EionRobb/purple-discord#128]
https://victorhurdugaci.com/github-releases-travis

This would be handy for users who look at Releases (or use things like [sibbell](https://about.sibbell.com/)).

**Comment by bobbybee** [comment]
AFAIK we're okay on CI for now, thank you for the suggestion though.

**Comment by aph3rson** [comment]
If I could make a slight update to this - GitHub now natively supports release-only subscriptions, which would notify subscribers when new releases are posted.

You don't have to use Travis, but posting to the releases page for major updates would be a great addition.

**Comment by alexolog** [comment]
It would specifically help the users that rely on Windows binaries.  While those that compile from source can just follow commit notifications, we never know when a new dll is available.

**Comment by aph3rson** [comment]
That would mean the only way to get notifications would be to subscribe to commits. Often times there's multiple commits per day, all of which would be useless (as the build wouldn't be run until that evening, FWICT).

Uploading that nightly build to the releases section would reduce those unnecessary notifications, which is what myself and @alexolog are asking for here.

Utilizing Releases through the GitHub API should be relatively simple - a POST request to [create the release](https://developer.github.com/v3/repos/releases/#create-a-release), and a POST request to [attach an asset](https://developer.github.com/v3/repos/releases/#upload-a-release-asset). Is it possible that this could be added to the same process that builds/stores the binary on robbmob?
