### ISSUE TITLE
Add discord icons to repo

### ISSUE THREAD

**Issue by rdvl97** [EionRobb/purple-discord#13]
I took the liberty of making this myself. The included zip folder contains png icons in 16px, 22px, 48px, and a scalable svg (as per the standard for icons in Pidgin/pixmaps/pidgin/protocols/).  I edited and rendered out the logo in inkscape.

https://mega.nz/#!ZdtHUAAB!Us6oh45TXMgTFW8D7O_htw8w4f4qb31IFMqAQK0Y4Ps

**Comment by EionRobb** [comment]
Oh, I already had some images, eg https://github.com/EionRobb/purple-discord/blob/master/discord16.png ?

I'll take a look at yours though :)

**Comment by rdvl97** [comment]
oh, oops i guess i shouldve checked again

**Comment by EionRobb** [comment]
So maybe we can put it to a vote as to which is better to use, cos I'm the worst person to decide :)
 
![discord](https://cloud.githubusercontent.com/assets/1063865/25163881/87108dec-2521-11e7-8e0e-ea06a2c15153.png) 👍 
or
![discord48](https://cloud.githubusercontent.com/assets/1063865/25163886/8a8ff390-2521-11e7-800e-9361826fa9bb.png) 🥇

**Comment by rdvl97** [comment]
here's how it looks in toast notifications btw: 
![image](https://cloud.githubusercontent.com/assets/3316274/25164318/ffeea458-2484-11e7-92e1-21febe8ffbbf.png)

**Comment by bobbybee** [comment]
Closing as there does not seem to be much interest and this issue is old.

**Comment by Slider-Whistle** [comment]
I disagree, there's 10 votes right there on users' preferred icon (what more do you expect on a github issue? I don't know how it was at the time of posting, but I'd call that overwhelming interest), and it does a lot to trick the user into thinking that they're using a complete, functional plugin.
That SVG is available at https://discordapp.com/branding by the way, this seems to be [the one people voted for](https://discordapp.com/assets/f8389ca1a741a115313bede9ac02e2c0.svg). Might be a good idea to make the center white rather of transparent.
