### ISSUE TITLE
ARM / Raspberry Pi 3

### ISSUE THREAD

**Issue by PandaBear77** [EionRobb/purple-discord#132]
Hello.
Since Discord does not run in ARM/Linux and the web version takes too much resources, this might be the only chance we have to be able access Discord on the Raspbian OS.
So, I have tried compiling,

```
git clone git://github.com/EionRobb/purple-discord.git
cd purple-discord
make
sudo make install
```

But gives a error during the compile,

```
root@raspberrypi:~/purple-discord# make install
make: hg: Command not found
mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/16
mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/22
mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/48
install -m 0644 -p discord16.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/16/discord.png
install -m 0644 -p discord22.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/22/discord.png
install -m 0644 -p discord48.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/48/discord.png
msgfmt -o po/es.mo po/es.po
make: msgfmt: Command not found
Makefile:114: recipe for target 'po/es.mo' failed
make: *** [po/es.mo] Error 127
```

Any help would be terribly appreciated.

UPDATE - There is a workaround by running "make -i install", the plugin builds and looks like it works, though I am not sure this is a complete functional build.

**Comment by EionRobb** [comment]
`msgfmt` is provided by the `gettext` package.  All you're missing out on is translations

**Comment by bobbybee** [comment]
(I can confirm that purple-discord does work on ARM fwiw)

**Comment by bobbybee** [comment]
Closing to inactivity
