### ISSUE TITLE
Compiling under Debian

### ISSUE THREAD

**Issue by MrFunken** [EionRobb/purple-discord#135]
Your compiling "how-to", don't seems really work. :/

```
tom@X1-Carbon:/tmp/purple-discord$ make
abort: there is no Mercurial repository here (.hg not found)
make: Nothing to be done for 'all'.
```

**Comment by bobbybee** [comment]
You might be able to ignore those. Is libdiscord.so created anyway? If
you run 'sudo make install', does it work?

**Comment by MrFunken** [comment]
Okay, you're right. I simply can ignore it :)
