### ISSUE TITLE
User nickname is not shown

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#14]
Example:
```
 {
    "nick":"Chai",
    "user":{
      "username":"Bianca",
      "discriminator":"5070",
      "id":"136923389951606784",
      "avatar":"413d22b2ffad0f864ecb32c570deeb81"
    },
    "roles":[
      "269266075567390720"
    ],
    "mute":false,
    "deaf":false,
    "joined_at":"2017-04-03T19:58:45.901000+00:00"
  },
```
Discord web interface shows the user as "Chai", and displays "Bianca#5070" in the properties.
If the nick is not available for a user, it displays the username (without the discriminator)
Pidgin always displays `<username>#<discriminator>` in the list of users and in the chat window.

**Comment by bobbybee** [comment]
I'm trying my hand at this.
