### ISSUE TITLE
auto-add treats groupings as channels

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#142]
A Discord server that has two groups with two channels in each:

```
+ Text Channels
+- text-1
+- text 2

+ Voice channels
+- voice 1
+- voice 2
```

Pidgin will create 6 buddies even though there should be only 4.

**Comment by bobbybee** [comment]
Discord channels can be grouped? Huh.

**Comment by alexolog** [comment]
Using the web interface:

![discord](https://user-images.githubusercontent.com/2112513/32530731-ce013f18-c40d-11e7-8968-b80111225db7.jpg)

**Comment by bobbybee** [comment]
Huh, okay.

**Comment by alexolog** [comment]
Can this please be looked at?

**Comment by bobbybee** [comment]
Resolved in pending MR.

**Comment by alexolog** [comment]
How will they be treated?
