### ISSUE TITLE
Automatically escaped markwdown

### ISSUE THREAD

**Issue by DuendeInexistente** [EionRobb/purple-discord#145]
While I understand that pidgin -and other libpurple clients I guess- has it's own formating bar, I found it pretty annoying that formating characters (\*) are automatically skipped when typed directly into the chat window, since moving the mouse and pressing a button is more awkward to me than just typing asterisks. Could this be made into a toggleable setting, at least? I doubt I'm the only one who's way more used to formatting manually when using Discord.

Of course I'm assuming it's something being done by the plugin, here. Feel free to correct me if it's my client doing it.

**Comment by bobbybee** [comment]
It could definitely be a toggleable settings, but hear out the case for
the current behaviour at least:

- Markdown is not standardised across prpls. HTML (what the formatting
  toolbar outputs internally) is. One of Pidgin's design goals is for
  the user to "forget" that they're having a conversation in a
  particular chat protocol, which means behaving uniformly across prpls
  when there's no good reason not to.

- Even on Discord proper, markdown is not inherently obvious to many
  people. I love markdown -- I have written tens of thousands of words
  formatted in pandoc markdown -- but as far as user friendliness,
  having the toolbar there is still easier I imagine.

- You don't have to click; there are keyboard hot-keys. Ctrl-b for bold,
  Ctrl-i for italics, etc. Depending on keyboard layout, that may be
  -more- efficient than markdown. Additionally, as far as UI goes, these
  hotkeys are familiar, I think, given their role in the various office
  suites. I have found myself trying to use them on the proprietary web
  client, heh.

- Given the above, there's still a case for having markdown as a
  formatting interface across all protocols. This is something I would
  definitely be interested, and I could see bitlbee benefitting from.
  But you'd have to take that up with the main Pidgin and libpurple devs
  :)

If all of the above can't convince you, well, okay. Feel free to send a
PR adding a fix. discord_escape_md is where the magic is, so you want to
short circuit that by checking an option. Add the bool option to
discord_add_account_options. Use purple_account_get_bool to check it.
Else poke one of us and we might get to it, time dependent.

Thoughts?

**Comment by DuendeInexistente** [comment]
What bothers me is specifically discord_escape_md, more than lack of md support being included programwide. And I'd add a toggle if I could, but my skill doesn't go much beyond very simple scripting.

**Comment by bobbybee** [comment]
This is an issue with Pidgin, not the prpl; at least one alternative libpurple frontend compatible with purple-discord allows for markdown input directly. The prpl is behaving appropriately given libpurple's decoupled design, cleanly separating frontend interface concerns from protocol details; if markdown input in Pidgin is desired, Pidgin -- not purple-discord -- should be modified. Closing.
