### ISSUE TITLE
Unread group DMs crashing Pidgin

### ISSUE THREAD

**Issue by zergling-man** [EionRobb/purple-discord#147]
If a group DM has unread messages when Pidgin boots, it crashes with a segfault that is "no fault of my own". On occasion this will also happen if Pidgin has already been running, but that's rather infrequent. It doesn't crash if a group DM receives a new message while Pidgin is open.

```
[wisknort@Xiao-Che ~]$ pacman -Qi purple-discord-git
Name            : purple-discord-git
Version         : v0.0.r0.g4c4c480-1
Architecture    : x86_64
Build Date      : Fri 16 Jun 2017 12:23:06 AEST
Install Date    : Fri 16 Jun 2017 12:23:06 AEST
[wisknort@Xiao-Che ~]$ uname -a
Linux Xiao-Che 4.14.0-1-MANJARO #1 SMP PREEMPT Wed Nov 8 23:54:55 UTC 2017 x86_64 GNU/Linux
[wisknort@Xiao-Che ~]$ pidgin --version
Pidgin 2.12.0 (libpurple 2.12.0)
```

**Comment by bobbybee** [comment]
Are you using purple-discord from the Fedora repos, perhaps? That
version is outdated; the latest master should not have this issue.
(Compiling is fairly simple.) This bug was fixed a few months ago, I
thought...

**Comment by zergling-man** [comment]
I'm using the AUR *-git package. Apparently it doesn't notify me of updates despite `yaourt -Syyu`. Thankyou.

**Comment by bobbybee** [comment]
Sure. If it's fixed, please close the issue :)
