### ISSUE TITLE
Chat History Not Shown

### ISSUE THREAD

**Issue by en3r0** [EionRobb/purple-discord#152]
Not sure if this is an issue on my end, but when joining a chat the previous messages are not displayed, including mentions.

**Comment by bobbybee** [comment]
This is fixed in the history branch which has not been merged due to
disputes over how to work around libpurple limitations (There is no sane
history API; once you consider multiple device issues, it's a mess.)

**Comment by Penaz91** [comment]
I have a similar problem, I get notified of the new messages, but when I go look at the chat, there are no new messages.

**Comment by Valinwolf** [comment]
This is one of the biggest issues for me. I can deal with only retrieving the last 20-30 messages, as long as I get _some_ of the recent history.

**Comment by alexolog** [comment]
History (other than the locally saved one) does not work for me.  Is there a command I'm missing?

**Comment by dlmarquis** [comment]
Fixed by #353
