### ISSUE TITLE
Disable/mute notifications for a channel

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#156]
In the web interface, I can turn off notifications and mute a channel.

I found no way to do it in Pidgin.  Some channels on a server hold no interest for me, but they keep popping up when somebody mentions `@everybody`.

Is there a way to block those notifications?

![notifications](https://user-images.githubusercontent.com/2112513/33645673-fa9baba4-da19-11e7-86eb-608554cf19ff.jpg)

**Comment by alexolog** [comment]
The "large channel" setting can approximate this but the granularity is too coarse.
We need a per/channel setting, and preferably a default one for channels that were not added

please also see #160.

**Comment by instinctualjealousy** [comment]
I'm having this issue, but it's popping up on just on mentions of @everybody, but on any. message. at all. It's really annoying. I can't even client side block it in pidgin with a whitelist.

**Comment by alexolog** [comment]
Can this please be looked at?
