### ISSUE TITLE
captcha required

### ISSUE THREAD

**Issue by thundergreen** [EionRobb/purple-discord#158]
hi all .. 
suddenly I get captcha error:Please see logs:

```
30879: 2017-12-12 17:16:52,595 INFO  libpurple: util:parsed 37                                                           
30879: 2017-12-12 17:16:52,596 INFO  libpurple: discord:Got response: {"captcha_key": ["captcha-required"]}              
30879: 2017-12-12 17:16:52,597 INFO  libpurple: connection:Connection error on 0xb868d0f8 (reason: 2 description: Bad use
rname/password)                                                                                                          
30879: 2017-12-12 17:16:52,599 INFO  libpurple: account:Disconnecting account thundergreen@gmail.com (0xb868b798)        
30879: 2017-12-12 17:16:52,600 INFO  libpurple: connection:Disconnecting connection 0xb868d0f8                           
30879: 2017-12-12 17:16:52,600 INFO  libpurple: connection:Destroying connection 0xb868d0f8                              
30879: 2017-12-12 17:16:52,773 ERROR backend: g_log purple_account_disconnect: assertion '!purple_account_is_disconnected
(account)' failed                                                                                                        
30879: 2017-12-12 17:16:52,773 INFO  libpurple: account:Destroying account 0xb868b798                                    
30879: 2017-12-12 17:16:56,486 INFO  libpurple: util:Writing file prefs.xml to directory /var/lib/spectrum2/discord.dnsfo
r.me                                                                                                                     
30879: 2017-12-12 17:17:04,952 INFO  libpurple: util:Writing file /var/lib/spectrum2/discord.dnsfor.me/prefs.xml         
30879: 2017-12-12 17:17:06,185 INFO  libpurple: util:Writing file accounts.xml to directory /var/lib/spectrum2/discord.dn
sfor.me                                                                                                                  
30879: 2017-12-12 17:17:06,185 INFO  libpurple: util:Writing file /var/lib/spectrum2/discord.dnsfor.me/accounts.xml      
30879: 2017-12-12 17:17:06,936 INFO  backend: Exiting...     
```

Is there any hint? I am using spectrum2 Manager to run this transport.

Any help appreciated

**Comment by bobbybee** [comment]
Hmm, haven't seen this before. In theory we could display the captcha
with librecaptcha (although that would add quite a bit of complexity to
the design, as librecaptcha is written in python and has a number of
deps), although I don't know why this would suddenly become a problem.

Eion, thoughts?

**Comment by thundergreen** [comment]
Yes I dunno why this happens now ..it worked weeks ago and suddenly it
stopped with those messages ....

Am 12.12.2017 22:48 schrieb "Alyssa Rosenzweig" <notifications@github.com>:

**Comment by thundergreen** [comment]
@bobbybee do u think we can try a workaround? started the transport new this morning and after several messages same issue. dunno where to start.

**Comment by thallada** [comment]
You need to somehow get Discord to mark your IP address as "okay". Log into discord using a browser on the same machine and complete the captcha or answer the email they might send you. If it is a server, you could try [installing an openvpn server on it](https://github.com/Nyr/openvpn-install), connect to it from a computer that has a browser so you have the same IP as the server, and log into Discord.

**Comment by bobbybee** [comment]
Oh! If that's all it is, a workaround that does not require proprietary
software (Discord) would be to login with
[harmony](https://github.com/nickolas360/harmony) which is able to work
with CAPTCHAs.

**Comment by nickolas360** [comment]
I recently added support for login attempts that require CAPTCHAs, as well as verification emails for login requests from new IP addresses, to [Harmony](https://github.com/nickolas360/harmony), which as @bobbybee noted, should serve as a workaround.

Once you can log in successfully with Harmony, purple-discord should be able to log in (at least for a while) without any issue.
