### ISSUE TITLE
Off-by-one in history loading

### ISSUE THREAD

**Issue by ghost** [EionRobb/purple-discord#159]
When opening a room from the buddy list, all but the most recent message get loaded into the scrollback. This behaves consistently, i.e. if I leave Pidgin offline for a while and open it later, the previous missing message gets filled in at the top of other new ones, and opening/closing the chat repeatedly doesn't cause the last message to appear.

**Comment by hoodieak** [comment]
bump

**Comment by JockeTF** [comment]
I've noticed this as well!

**Comment by alexolog** [comment]
When I open a room from the list, no past messages get loaded at all (other than from the enhanced history plugin).
