### ISSUE TITLE
notifications are on by default

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#160]
If I click on an invitation to a Discord server, and open it in the web browser, Pidgin immediately starts opening tabs and displaying every message sent on every channel of that server, which is very distracting and annoying for servers with many active channels.

I think that the large channel setting is ignored in this case.

(and I also believe that this mechanism, even if it worked as intended, is too coarsely granulated.  See #156)

Note: auto-create feature is off, large channel threshold is set to 3.

**Comment by alexolog** [comment]
Can this please be looked at?

**Comment by EionRobb** [comment]
There was an issue where new chat windows and new servers were treated as having 0 users, instead of the actual number.  I've since fixed that timing so that it doesn't treat empty rooms as being below the large-user-count number
