### ISSUE TITLE
Pidgin groups keep moving to the top

### ISSUE THREAD

**Issue by tpenguinltg** [EionRobb/purple-discord#163]
Whenever the account is enabled and reconnected, or connected for the first time, the default groups created for each server (guild?) keep moving to the top of the buddy list, even after I've moved them around.

**Comment by bobbybee** [comment]
I can confirm this (and I agree it's annoying but I'm not sure how to
fix)

**Comment by bobbybee** [comment]
:tada:

**Comment by EionRobb** [comment]
#165 isn't quite right.
