### ISSUE TITLE
Finch crashing on big rooms

### ISSUE THREAD

**Issue by UltimatePancake** [EionRobb/purple-discord#17]
Hey man, finch crashes with a `SIGSEGV (Address boundary error)` message (on fish) or a `Segmentation fault (core dumped)` message (on bash) when entering rooms with tons of people (hasn't happened to me on smaller ones. Any ideas as to what could cause this? Looking for logs in the meantime.

Been waiting for this plugin for a while, many thanks!

**Comment by EionRobb** [comment]
Can you use https://developer.pidgin.im/wiki/GetABacktrace to get a backtrace and attach to this issue?
