### ISSUE TITLE
Join /leave messages are flooding my chat window

### ISSUE THREAD

**Issue by thundergreen** [EionRobb/purple-discord#171]
Help! I don't know why but since I made a spectrum 2 upgrade I get plenty of join / leave notifications 

That's not really cool see:

![screenshot_20180203-081426](https://user-images.githubusercontent.com/13320319/35764120-2010d6be-08bb-11e8-88bf-85114bf12d86.png)

**Comment by thundergreen** [comment]
No idea? Nobody facing those issues ?

**Comment by dshanske** [comment]
I am. If you find a solution...

**Comment by bobbybee** [comment]
IIRC it's pretty easy to hide these messages entirely through a Pidgin
preference (or perhaps a plugin?)

**Comment by thundergreen** [comment]
Should be just deactivated by  the purple plugin

**Comment by thundergreen** [comment]
If I well remember before last commit I didn't have those messages

**Comment by kabili207** [comment]
You can remove these by enabling the "Join/Part Hiding" plugin.

**Comment by thundergreen** [comment]
@kabili207 i use spectrum in docker mode..dunno how to install those plugin ..any idea?

**Comment by kabili207** [comment]
I probably should have updated my message. I found out later that the plugin I mentioned only helped a little. I ended up patching Finch to not display join/part messages at all. Not really a viable solution for you.

**Comment by thundergreen** [comment]
@kabili207 how would i do that ?

**Comment by thundergreen** [comment]
Hello DEv. Can we PLEAASSEEE Deactivate this annoying messages... THis makes the purple-discord unusable :(

**Comment by thundergreen** [comment]
I don't understand why nobody is interested to fix this issue .. As it floods the chat history in a really annoying manner

**Comment by EionRobb** [comment]
@thundergreen happy to have patches, but unfortunately as I don't see any join/part's on Pidgin I wouldn't know if it's fixed or not.  Does it just happen when a user goes offline, or is there some other behaviour?

**Comment by thundergreen** [comment]
In our test room I only get leave messages from u but not vt.

**Comment by bobbybee** [comment]
From poking around with the prpl in a new frontend, it would appear the system messages are from libpurple itself. It looks like there's a `quiet` option, though. Investigating...

**Comment by bobbybee** [comment]
Resolved, update your purple-discord :grin:
