### ISSUE TITLE
Can't download libdiscord.dll file.

### ISSUE THREAD

**Issue by flippinriverrat** [EionRobb/purple-discord#173]
Is there another upload of this somewhere I can get? The eion.robbmob.com site won't connect.

**Comment by EionRobb** [comment]
Sorry about that.  Server seems to be pretty flaky. :(
[libdiscord.zip](https://github.com/EionRobb/purple-discord/files/1831858/libdiscord.zip)

**Comment by flippinriverrat** [comment]
Thank you so much!
