### ISSUE TITLE
Error while compiling on MX Linux (Debian based)

### ISSUE THREAD

**Issue by ktlinux** [EionRobb/purple-discord#176]
sudo make install
mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/16
mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/22
mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/48
install -m 0644 -p discord16.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/16/discord.png
install -m 0644 -p discord22.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/22/discord.png
install -m 0644 -p discord48.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/48/discord.png
msgfmt -o po/ru.mo po/ru.po
make: msgfmt: Command not found
Makefile:123: recipe for target 'po/ru.mo' failed
make: *** [po/ru.mo] Error 127

**Comment by JockeTF** [comment]
Try this first:

```
sudo apt-get install gettext
```

**Comment by ktlinux** [comment]
Done that. Now it's fixed

**Comment by EionRobb** [comment]
Thanks, @JockeTF :)
