### ISSUE TITLE
Join voice channels as chat

### ISSUE THREAD

**Issue by klobes5** [EionRobb/purple-discord#178]
Is there any specific reason why this can't support joining voice/chat channels as text only? I'm willing to contribute but curious what that would entail beyond the logic that simply errors if channel type is voice

**Comment by bobbybee** [comment]
Er, purple-discord aside for a moment -- is it even possible to join
voice channels as text? (Is this a new feature maybe?)

**Comment by klobes5** [comment]
You may be right
