### ISSUE TITLE
Sending a message with an emoji crashes pidgin

### ISSUE THREAD

**Issue by user234683** [EionRobb/purple-discord#181]
This the the emoji I tested with: 👌
Sending it to any person in discord (group chat or not) will crash pidgin, at least on my system. With the fonts I have, emojis render as lego bricks like so:
![lego](https://user-images.githubusercontent.com/28744867/39962579-a8651cc0-5607-11e8-9ad2-d8ec6e94cb75.png)

The crash is a "Microsoft Visual C++ Runtime Error". Here is the crash info:
```
 Problem Event Name:	APPCRASH
  Application Name:	pidgin.exe
  Application Version:	2.12.0.0
  Application Timestamp:	58c20b6e
  Fault Module Name:	libglib-2.0-0.dll
  Fault Module Version:	2.28.8.0
  Fault Module Timestamp:	4e253544
  Exception Code:	40000015
  Exception Offset:	0004c2d8
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	238b
  Additional Information 2:	238b3f5dc362bc7bd19e92718a00baca
  Additional Information 3:	66a4
  Additional Information 4:	66a4552d2deb2a17b52ab5e23d694f8c
```

Similar to #180, #161, and #148, pidgin will crash at start if the message was sent to a chat set with auto-join, until you disable autojoin. The crash when restarting is exactly the same except the additional information is different:
```
  Additional Information 1:	6902
  Additional Information 2:	6902495419868fa668b9bc6c7310f47e
  Additional Information 3:	d37d
  Additional Information 4:	d37d49d82e8a2246d3f19c033f2a2603
```
Also, the message is logged locally and sent to the other person.

**Comment by EionRobb** [comment]
Can you paste the last crash listed in your %appdata%\.purple\Pidgin.RPT file?

**Comment by bobbybee** [comment]
I cannot reproduce this issue on Debian Buster, latest purple-discord
compiled from master, Pidgin from the repository.

**Comment by EionRobb** [comment]
is it the same as #180 ?  Is the emoji being sent as `:ok_hand:`?

**Comment by user234683** [comment]
@EionRobb The error doesn't seem to be logged to Pidgin.RPT (the file isn't being written to when I do a crash). Only #180 seems to be logged there. The emoji isn't being sent as `:ok_hand:`, I'm copy and pasting the Unicode character U+1F44C. Interestingly, when I pasted the character into python's IDLE 3.6 to get the code point, it crashed that too. I'll have to look into that to see if it's related. Can anyone test this on windows?

**Comment by EionRobb** [comment]
Can't reproduce on windows after the latest round of patches, if you want to try updating the dll and try again?
![image](https://user-images.githubusercontent.com/1063865/39972198-0a7db94c-575e-11e8-8b92-bb5b3748f72d.png)

**Comment by user234683** [comment]
@EionRobb Still crashing even with the updated module. No error logged to pidgin.RPT still

**Comment by user234683** [comment]
I've figured out this happens with any character outside the BMP unicode plane. So 𠑗 will crash both pidgin discord and python IDLE. So this is likely related to surrogate pairs.

Info when using --debug:
```
Date: Sun, 13 May 2018 22:25:28 GMT

Content-Type: application/json

Connection: close

Strict-Transport-Security: max-age=31536000; includeSubDomains

Via: 1.1 google

Alt-Svc: clear

Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"

Server: cloudflare

CF-RAY: [omitting this...]



'
**
Json:ERROR:json-scanner.c:895:json_scanner_get_unichar: assertion failed: (g_unichar_validate (uchar))
```

Build info:
```
Pidgin 2.12.0 (libpurple 2.12.0)
unknown

Build Information
  Plugins: Enabled
  SSL: SSL support is present.
  GTK+ Runtime: 2.16.6
  Glib Runtime: 2.28.8

  Library Support
    Cyrus SASL: Enabled
    Gadu-Gadu library (libgadu): External
    GtkSpell: Enabled
    GnuTLS: Disabled
    Network Security Services (NSS): Enabled
    Perl: Disabled
    Tcl: Disabled
    Tk: Disabled
    UTF-8 DNS (IDN): Disabled
    Voice and Video: Disabled
```

**Comment by EionRobb** [comment]
@user234683 can you try downloading the Non-BMP Filter plugin from https://code.google.com/archive/p/pidgin-win32-non-bmp/downloads and see if that resolves the crashing?

**Comment by user234683** [comment]
Here's the exact file where the error occurs:
https://gitlab.gnome.org/GNOME/json-glib/blob/9a647104ca77d4c4272845fed4bfae028098afd3/json-glib/json-scanner.c
at line 895: `g_assert (g_unichar_validate (uchar));`

This is then fixed in the next commit:
https://gitlab.gnome.org/GNOME/json-glib/blob/fcd07918d3ed2b31b047900da9d2fed23dddf7da/json-glib/json-scanner.c
line 895: `g_assert (g_unichar_validate (uchar) || g_unichar_type (uchar) == G_UNICODE_SURROGATE);`

According to https://gitlab.gnome.org/GNOME/json-glib/tags?page=2&sort=updated_desc, this would imply the version of the module being used is anywhere between 0.5.0 and 0.10.4

The file for for libjson I have is named libjson-glib-1.0.dll. The version number in the name seems to be wrong, as that version came much later than 0.10.4 which is the upper bound. The date modified on the file coincides with the date modified on libsteam-1.6.1.dll. So it must have come from https://github.com/EionRobb/pidgin-opensteamworks/raw/master/steam-mobile/libjson-glib-1.0.dll when I installed the steam plugin.

I'll try the non-bmp filter

**Comment by user234683** [comment]
Nope, the Non-BMP plugin didn't fix the crash. I verified I installed it correctly, as it shows up in plugin information.

**Comment by user234683** [comment]
Replacing libjson-glib-1.0.dll with the version from https://github.com/EionRobb/skype4pidgin/raw/master/skypeweb/libjson-glib-1.0.dll as indicated in the instructions [here](https://github.com/EionRobb/purple-discord) fixes the bug.

**Comment by EionRobb** [comment]
The library is called json-glib-1.0, and the version of that in the Steam plugin, and some other plugins is 0.8.0.  If you grab a copy of libjson-glib-1.0.dll from https://github.com/EionRobb/skype4pidgin/raw/master/skypeweb/libjson-glib-1.0.dll then it should be version 0.14.2 of libjson-glib-1.0 :)

**Comment by EionRobb** [comment]
Yay, nice.  Glad you got it working.  The newer json-glib is backwards compatible.  It's also a requirement to use the newer json-glib with the Facebook and Hangouts plugins :)

**Comment by user234683** [comment]
Perhaps it should be updated in the instructions for the steam plugin

**Comment by EionRobb** [comment]
Sounds good.  I've updated the dll there.
