### ISSUE TITLE
Buddy information stopped working

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#185]
Both ctrl-O in a chat and right-click / Get Info on a buddy in the list display "Information: Retrieving..." which does not resolve.

**Comment by bobbybee** [comment]
I cannot reproduce this on Debian buster.

**Comment by alexolog** [comment]
Happens on Windows 10

**Comment by alexolog** [comment]
Nothing suspicious in the log

**Comment by EionRobb** [comment]
Which log is that? Can you attach?

**Comment by alexolog** [comment]
The debug window, and I'd rather not since it contains information that I consider to be private

**Comment by andreygursky** [comment]
This should be fixed by https://github.com/EionRobb/purple-discord/pull/188.

**Comment by EionRobb** [comment]
Oh, good point, @andreygursky 
@alexolog  can you try grabbing a new dll from https://eion.robbmob.com/libdiscord.dll and try again?

**Comment by alexolog** [comment]
Works perfectly!  Thank you!
