### ISSUE TITLE
User name/discriminator changes aren't reflected

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#199]
If a user changes their username or discriminator (number suffix thing) in discord, they appear as a new user in Pidgin, in the Discord group, rather than having the existing buddy renamed to match

This needs to be checked in two places:
* during login
* during user updated event

**Comment by bobbybee** [comment]
I can confirm this happening (a friend of mine changed her nick, way
back when)

**Comment by bobbybee** [comment]
Duplicate of #70
