### ISSUE TITLE
Voice channels joinable as text channel

### ISSUE THREAD

**Issue by rdvl97** [EionRobb/purple-discord#2]
also, sadly there's no secret text channel hidden in the voice channel.  sending a message to the channel just yields this response: `(23:09:44) discord: Got response: {"code": 50008, "message": "Cannot send messages in a voice channel"}`

**Comment by rdvl97** [comment]
my apologies, i did not expand the channel browser window enough to see the markers distinguishing between voice and text channels

**Comment by EionRobb** [comment]
Probably shouldn't show voice channels in there in the first place?

**Comment by rdvl97** [comment]
well, maybe it will be possible in the future to write a plugin that can access these channels

**Comment by rdvl97** [comment]
idk, i feel that its still somewhat useful to have it visible in the browser

**Comment by EionRobb** [comment]
Would it be better if they weren't joinable at the moment until voice support arrives (if it does)?

**Comment by rdvl97** [comment]
that sounds good

**Comment by p4plus2** [comment]
You can no longer join voice channels as text.  Closing for now.
