### ISSUE TITLE
Groupchat typing notification in conversation window breaks after initial notification

### ISSUE THREAD

**Issue by Eloston** [EionRobb/purple-discord#21]
I'm using the lastest code from your pidgin-groupchat-typing-notifications and the latest code from this repository.

**The setup**: I tested this in an empty server except two users (which includes myself). I am logged into Pidgin only, and the other user is using the web interface.

**The problem**: When the other user starts typing, then I can see their notification. But after the message is sent, I don't see any more notifications from them. Then when I start typing from Pidgin, I can see that the other user and I are typing. When I have sent my message, I can't see any more notifications when either of us type.

However, the other user can still see typing notifications start and end normally the entire time.

On another note (but probably not helpful), direct messages are not affected.

I'm not sure which plugin is at fault, so I apologize in advance if I'm making noise in the wrong repository.

**Comment by Eloston** [comment]
With the latest code from `master` at the time of writing (085f0da7027ed883da2cfd1c93f07da6cb770930), I'm not seeing any typing notifications in group chat anymore. However, one-on-one chats still work just fine and other users can see typing notifications from me normally too.

Sorry if I'm creating noise, as it seems there's some refactoring in progress.

**Comment by nipos** [comment]
Still doesn't work at all.
I really want to see who's writing.
Please fix that.

**Comment by bobbybee** [comment]
Closed by #73 

Note that this requires https://github.com/EionRobb/pidgin-groupchat-typing-notifications to be installed to work.
