### ISSUE TITLE
Authentication error with Spectrum2

### ISSUE THREAD

**Issue by edhelas** [EionRobb/purple-discord#212]
I'm trying to use this lib using Spectrum2.
The setup seems to work fine however I'm not able to authenticate using my credentials (that are working using purple-discord on a standard Pidgin client).

Any idea of what did I missed?

```xml
<message to='test@movim.eu/11939641707904944853168251682' from='discord.movim.eu' type='chat'>
	<archived xmlns='urn:xmpp:mam:tmp' by='test@movim.eu' id='1543582301449235'/>
	<stanza-id xmlns='urn:xmpp:sid:0' by='test@movim.eu' id='1543582301449235'/>
	<spectrumerror xmlns='http://spectrum.im/error' error='2'>CONNECTION_ERROR_AUTHENTICATION_FAILED</spectrumerror>
	<body>Bad username/password</body>
</message>
```

**Comment by edhelas** [comment]
Closing the ticket at is seems to work now.

**Comment by bodqhrohro** [comment]
How did you get it to work?

I have exactly the same problem.

**Comment by bodqhrohro** [comment]
Okay, looks like I had to log in via a browser from the same IP, hit HCaptcha and confirm the IP via e-mail.
