### ISSUE TITLE
Filter @here notifications

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#213]
Can we filter out @here notifications if the channel window is not open?

**Comment by johndoe71rus** [comment]
I am new to discord. Is this related to the appeal by user group / role? example @users @testers

**Comment by SoraHjort** [comment]
It's not related to a usergroup/role. It's a global discord @ tag that every channel has. Another is "everyone".

The difference between the two is @here is for those who are in a specific #room where as @everyone is everyone on the discord channel.

On Discord's app, you have the option to mute those, so you don't get those confused when you, the individual is being @ at. However Pidgin ignores that rule.

However, what is really annoying is that when a channel uses either of those two, it not only opens up a tab or window for that chat, it then brings it up front stealing focus. It's annoying cause I'll be typing away, or playing a game and then BAM! it takes focus away.

So it'd be nice if those were filtered out if the chat windows weren't open. Or atleast look at the user settings on whether or not those tags are muted.

**Comment by EionRobb** [comment]
I've just added in a setting that disables chat windows from opening whenever there's a mention (user, role, here or everyone)

**Comment by alexolog** [comment]
Can't we have it per-server like the official client does?

https://support.discordapp.com/hc/en-us/articles/215253148-How-do-I-stop-everyone-mentions-from-select-servers-

https://support.discordapp.com/hc/en-us/articles/209791877-How-do-I-mute-and-disable-notifications-for-specific-channels-

**Comment by johndoe71rus** [comment]
>  disables chat windows from opening whenever there's a mention (user, role, here or everyone)

I want to separate 2 situations.
1. Open the window / tab of the channel where I was mentioned, if this channel was not open before
2. Do not bring up the pidgin window when I was mentioned
Which option does the setting decide?
