### ISSUE TITLE
No error is shown when a message longer than 2000 characters is sent

### ISSUE THREAD

**Issue by joker314** [EionRobb/purple-discord#219]
#### Current Behaviour
Discord has a character limit of 2000 characters. When a message is sent which is longer than 2000 characters, the chat client (I'm using Pidgin) does not give any indication to the user that the message was not sent.

However, the recipient will not receive the message.

#### Suggested Behaviour
If a message longer than the character limit is sent, show a warning (in bold) which explains to the user that their message was not sent

**Comment by alexolog** [comment]
Does this plug-in work for you?
https://bitbucket.org/rekkanoryo/purple-plugin-pack/src/default/splitter/

**Comment by joker314** [comment]
Tested patch: it works.

**Comment by EionRobb** [comment]
Thanks for testing and coming back to let us know, @joker314  :)
