### ISSUE TITLE
Add option for opening channel group chat on activity or username mention

### ISSUE THREAD

**Issue by Eloston** [EionRobb/purple-discord#22]
It would be nice to have an option to open a channel group chat window when the own user's username is mentioned.

The reason I would like this is there's no way to receive a mention if it's from a channel not already joined by Pidgin.

**Comment by bobbybee** [comment]
Alternatively, depending on configuration, any activity should open the chat as noted in #28

**Comment by bobbybee** [comment]
@Eloston See #79 :smile:

**Comment by Eloston** [comment]
@bobbybee Just tried it and it works well. Thanks!
