### ISSUE TITLE
Minor: Some server emojis are shown as code

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#224]
Discord nitro allows for custom server emojis to be sent in direct messages.
When pidgin is on the receiving side, said emojis are shown with a code like the following
```
<a:bolbhyperparty:425792724810072084>
```
or
```
<a:bolbdab:454470464668958730>
```
The emojis seem to be visible from `https://cdn.discordapp.com/emojis/425792724810072084` and `https://cdn.discordapp.com/emojis/454470464668958730`
Other emojis are instead shown with their name inside a link.

Could it be cause the emojis shown are animated?

Thanks for your attention.

**Comment by Penaz91** [comment]
> Since when are animated emojis a thing? :P
I think it's a recent thing. Or maybe not, I have no idea.

> Could you try the branch `animated-emojis` and see if that resolves the issue? (And also, test if it regresses regular emojis?)

I'm building the plugin now, I'll let you know asap

**Comment by Penaz91** [comment]
The issue is partially solved, seems that the link given by the plugin adds a ".png" extension at the end, which doesn't allow the animation to happen (it is a still frame). According to my very few experiments, such extension is not necessary to view the animation, as well as for still emojis.
There is no damage done to the normal emojis and emoticons.
I'd say it's good enough :+1:

**Comment by bobbybee** [comment]
> The issue is partially solved, seems that the link given by the plugin
> adds a ".png" extension at the end, which doesn't allow the animation
> to happen (it is a still frame). According to my very few experiments,
> such extension is not necessary to view the animation, as well as for
> still emojis.

Resolved (extension removed) and merged into master.

**Comment by Penaz91** [comment]
Works like a charm.
Amazing as always, thank you a lot!

**Comment by alexolog** [comment]
I can't make the animated emojis animate.  What am I missing?

**Comment by Penaz91** [comment]
Hi, this could be a different issue from what was presented here, I suggest you open a new issue specifically for your problem, you should include the following information:
- The plugin version you're using (in pidgin you can see it from help->plugin information)
- The libpurple client you're using (pidgin, bitlbee, adium, ...)
- Do the animated emojis show as code like in this issue, or do they show as a still frame?
- A list of the plugins you're using (this will be useful to reproduce your problem in case it's due to incompatibility between plugins)
- Your operating system: Linux Distribution (like Ubuntu, ArchLinux, Artix, Gentoo), Windows, MacOS

Another useful information could be any errors shown in the debug screen (if you're using pidgin), you can filter the messages by using "discord" as a search string, in case the log is really long, I suggest using pastebin or include a file, instead of pasting everything here.

If you have any question don't be afraid to ask.
Have a nice day!

**Comment by alexolog** [comment]
Done.   #260
