### ISSUE TITLE
Add user role info

### ISSUE THREAD

**Issue by Eloston** [EionRobb/purple-discord#23]
I have two ideas relating to user roles that would be nice to have:

1. For users with special roles such as Owner, Moderator, Bot, etc., place special icons next to their name and sort them above others in the member list
2. Add a method of retrieving the list of all user roles. ~Perhaps using the dialog used to get more user info will work.~ EDIT2: The "Buddy Information" dialog box doesn't work for this.

EDIT: This isn't related to the general topic of this issue, but adding availability status (Online, Idle, Do Not Disturb) and the game status to the more info dialog box would be nice too.

**Comment by EionRobb** [comment]
We're working on the first one - the tricky bit is that roles can be customised, whereas libpurple/Pidgin expects fixed roles, so we'll need to work out a way of comparing permissions to roles to work out which role is an admin

**Comment by EionRobb** [comment]
See also issue #16 which talks about roles not being used to work out who should show in a room

**Comment by Eloston** [comment]
How are you considering mapping permissions to emblems right now?

Also, adding info about a user's server/channel permissions to the user info dialog would be nice too.
