### ISSUE TITLE
add option to disable activating chat window when server owner speaks

### ISSUE THREAD

**Issue by zmike** [EionRobb/purple-discord#237]
For whatever reason, whenever the owner of a server speaks on a server it triggers a window activate request which forces the desktop to jump that chat window into focus. Having a method to disable this behavior would be really useful.

**Comment by zmike** [comment]
Actually, I'm not sure why any part of this plugin triggers window activate. No other messages on any other protocol I've used do this?

**Comment by EionRobb** [comment]
Just for fun.  Bloody annoying though :)

**Comment by alexolog** [comment]
@mentions do that as well, with no way to mute channels that abuse @everyone

**Comment by EionRobb** [comment]
Just added a setting that disables mentions from opening new chat windows :)

**Comment by alexolog** [comment]
Can't we have it per-server like the official client does?

https://support.discordapp.com/hc/en-us/articles/215253148-How-do-I-stop-everyone-mentions-from-select-servers-

https://support.discordapp.com/hc/en-us/articles/209791877-How-do-I-mute-and-disable-notifications-for-specific-channels-

**Comment by alexolog** [comment]
Also I noticed the opposite happening:
I got at-mentioned by name on a channel but the window never popped up.

**Comment by alexolog** [comment]
(didn't even open)
