### ISSUE TITLE
Add unread messages to channel window when joining

### ISSUE THREAD

**Issue by Eloston** [EionRobb/purple-discord#24]
Having this for when the user joins a channel that has been joined before and for joining new channels would be nice.

Maybe an option to configure how many of such messages to retrieve would be nice to prevent overloading the user (and potentially the client). A harcoded amount of 100 wouldn't be too bad either.

**Comment by EionRobb** [comment]
Issue #4 will also be fixed when we fix this

**Comment by bobbybee** [comment]
A naive solution is implemented for this, but it seems to cause more problems than not at the moment.

**Comment by alexolog** [comment]
What is the status of this issue?

**Comment by dlmarquis** [comment]
This was fixed in commit 1ec4d36944380258847557d37026bdfcb9a4915f.
