### ISSUE TITLE
Private channels/rooms list users that are not in there

### ISSUE THREAD

**Issue by stheno** [EionRobb/purple-discord#240]
As an admin in a server with hundreds of people, I see some private rooms that have regular members in the list on here but do not show in the Discord app or web interface.

**Comment by EionRobb** [comment]
That's a fun quirk of the Discord API:  it'll leak all the rooms on a server, even if you don't have permissions to see/join them.  The official apps/website will hide them.  The API also reveals the topic of the room, which users/admins might expect to be private also.
