### ISSUE TITLE
custom emoji as inline images do not animate

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#246]
Only the first frame is displayed.

At least provide a clickable url to the image.

**Comment by EionRobb** [comment]
Hmm.  I feel like this is a setting somewhere, but I can't seem to find it.
In the meantime, you can disable the inline images and go back to a url through the "Display custom emoji as inline images" advanced account setting

**Comment by alexolog** [comment]
It didn't work, I see a ":glomp:" instead in the log, while the official client shows an animation

**Comment by alexolog** [comment]
Apologies, worked well on 2nd try.

**Comment by alexolog** [comment]
Could not find the setting to enable animation, using inline images instead - not optimal but works

**Comment by alexolog** [comment]
So does that mean that inline animated emojis are not supported?
