### ISSUE TITLE
Auto-escaping asterisks is messed up

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#247]
Typed: `*test*`
Used CTRL-i to italicize
Sent to discord buddy
Result: `\test**`

**Comment by EionRobb** [comment]
What should it have converted it to, in this case, before sending.  `*\*test\**` ?

**Comment by alexolog** [comment]
What do you know?  This is a problem in the official client, and Pidgin actually treats it correctly.
Typing "*\*test\**" in Discord displays "\test**" there and the expected string in Pidgin.

**Comment by EionRobb** [comment]
Hmm... so should we be trying to match the official client or try and send what was intended

**Comment by alexolog** [comment]
I think it goes deeper.  Reddit also exhibits the same behaviour.  Apparently a markdown bug.

In general: Pidgin escapes the string correctly before sending it to Discord, and Discord messes it out.
Typing the same into Discord input box directly results in the mangled behaviour.

**Comment by alexolog** [comment]
Closing.
