### ISSUE TITLE
Channel and role mentions

### ISSUE THREAD

**Issue by Eloston** [EionRobb/purple-discord#25]
I tried using `@username#id` as well as omitting certain parts but they all don't work. Doing `<@id>` made the web client stylize that text like a username mention.

**Comment by EionRobb** [comment]
There's no way at the moment.

We might borrow the same idea that the [bitlbee-discord](https://github.com/sm00th/bitlbee-discord) plugin [does](https://github.com/sm00th/bitlbee-discord/blob/88de238b8317f9f19da6d12d786a66004a3f81e5/README#L105-L114) and try to see if someone typed "@EionRobb" or "EionRobb:" in order to mention them

**Comment by Eloston** [comment]
I'm not familiar with bitlbee-discord. What happens if there are two users with the same name but different IDs?

**Comment by Eloston** [comment]
Okay, so I found out after some experimentation that using `<@USER_ID>` where `USER_ID` is the ID of the user will properly notify the user. But this is probably some Discord feature I didn't know about before since it also works on the web client.

**Comment by Eloston** [comment]
So I looked into this a little bit earlier and I've come up with an idea. It involves overriding the tab-completion signal in Pidgin:

* Username mentioning: Replace strings of the format `@unicode_string#discriminator` with a mention. Tab completion logic is a bit complicated, though:
    * For regular ASCII-only usernames, behave similarly to Pidgin's default autocomplete behavior, except that it only functions if there's a `@` behind the cursor. That is, start matching from the beginning of the username and then show options if there are multiple usernames sharing the same prefix.
    * For unicode characters, ignore any characters that don't have an "ASCII-equivalent". Also, convert unicode characters to ASCII-looking equivalents.
        * But if there are already non-ASCII characters between the cursor and the last `@`, then follow the same behavior employed by ASCII-only usernames.
        * After a match has been found in either mode, replace the characters with the full unicode username.
    * If the cursor immediately follows a `@`, autocomplete the last person that mentioned us. If such person does not exist, then autocomplete the last person that sent a message. (I'm not entirely sure if this feature is a good idea, though)
    * If #14 gets implemented, then we want to be able to tab-complete either nicknames or usernames.
* Channel mentions: Replace strings of the format `#unicode_string`.
    * Autocompletions will be limited to channels existing within the currrent guild (unless we find some way of specifying a guild).
    * ASCII and Unicode behavior will work identically to what usernames have.

**Comment by EionRobb** [comment]
Overriding any UI-specific functions such as tab-completion would need to be done in a separate UI plugin, as not all libpurple clients would use tab-completion.  Otherwise, I really like it :)

**Comment by bobbybee** [comment]
Solved by PR #72

**Comment by bobbybee** [comment]
Reopening as channel mentions are still broken (although they seem to be rare in practice)

**Comment by alexolog** [comment]
Mentioning does not work for me.
When I write `@local_alias` it is not converted to a mention.
Pressing tab after the `@` does nothing.

Please advise.

**Comment by bobbybee** [comment]
Try local_alias:

**Comment by alexolog** [comment]
Sorry, by `local_alias` in this context I meant the actual local alias of the person, without the `#`

What is the actual format that I need to use to mention the local alias `Bob` for example?

**Comment by alexolog** [comment]
Also, is this the only way to mention?  `@` does not work?

**Comment by EionRobb** [comment]
@alexolog Pidgin doesn't support the `@username` syntax, as a workaround you can use tab-completion (without the @ sign) and the plugin will convert the tab-completed `username: ` into the `@username ` mention format that discord uses

**Comment by alexolog** [comment]
Got it, thanks
