### ISSUE TITLE
cppcheck: [libdiscord.c:1289] -> [libdiscord.c:1284]: (warning) Either the condition 'if(guild)' is redundant or there is possible null pointer dereference: guild.

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#254]
Since commit 48e8287, cppcheck gives a warning related to the discord_replace_channel function. Seems like the guild variable needs to be checked for NULL before looking up the channels member of the variable: 

```
[libdiscord.c:1289] -> [libdiscord.c:1284]: (warning) Either the condition 'if(guild)' is redundant or there is possible null pointer dereference: guild.
```

```
```
	DiscordGuild *guild = ag->guild;
	gchar *match_string = g_match_info_fetch(match, 0);
	gchar *channel_id = g_match_info_fetch(match, 1);
	gint64 channel_num = to_int(channel_id);
	DiscordChannel *channel = g_hash_table_lookup_int64(guild->channels, channel_num);

	if (channel) {
		/* TODO make this a clickable link */

		if (guild) {
			g_string_append_printf(result, "%s", discord_normalise_room_name(guild->name, channel->name));
		} else {
			g_string_append_printf(result, "#%s", channel->name);
		}
	} else {
		g_string_append(result, match_string);
	}
```
```

**Comment by pabs3** [comment]
This issue is fixed in git master, not sure which commit fixed it.

**Comment by EionRobb** [comment]
Whoops, fixed in https://github.com/EionRobb/purple-discord/commit/41282a0b3cc30d30af7ca40068283c75928df7d2

Sorry for not tagging this issue
