### ISSUE TITLE
Unicode emojis shown as tofu

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#258]
Unicode emojis shown as tofu

**Comment by bobbybee** [comment]
Which OS? On linux, pidgin+purple-discord seems ok.

**Comment by alexolog** [comment]
Windows 10.

**Comment by EionRobb** [comment]
Pidgin on Windows uses an old version of GTK that doesn't support emoji. 
There are a couple of unicode emoji smiley themes you can tell Pidgin to use to be able to render them, or manually upgrade your version of GTK

**Comment by alexolog** [comment]
Can you please point to instructions?  The GTK download page says:
"Note: These instructions are intended for developers wanting to create Windows applications based on GTK, not for end-users. On Windows, GTK applications are typically bundled with GTK already, so end-users do not need to worry about how to install GTK itself."

I tried following the directions and ended up with the whole MINGW, which I don't need.  Do I just replace the like-named DLLs?  Google is not very helpful.  Some guidance will be appreciated.

**Comment by alexolog** [comment]
And (of course) the naive approach did not work.
Please assist.

**Comment by alexolog** [comment]
After spending hours chasing DLL dependencies Pidgin started but none of the transport plugins loaded.  I give up.

**Comment by alexolog** [comment]
Even after switching to a smiley theme that supports UTF-8 emoji (Noto Emoji in my case) I still see tofu instead of the smileys.

**Comment by szr8** [comment]
On 11/18/2019 20:33 PM, Alex wrote:
>
> Even after switching to a smiley theme that supports UTF-8 emoji (Noto 
> Emoji in my case) I still see tofu instead of the smileys.
>
IIRC, you should be able to rename or delete [1] 
%ProgramFiles(x86)%\Pidgin\Gtk so that it uses that newer GTK which 
should be registered globally (in %PATH% and such.) If that doesn't 
work, you can try replacing [1] %ProgramFiles(x86)%\Pidgin\Gtk with [1] 
%CommonProgramFiles(x86)%\GTK, though simply removing the one in the 
Pidgin directory should work.


[1] Use %ProgramFiles% and %CommonProgramFiles% if using 32-bit windows.

**Comment by alexolog** [comment]
Where do I get a "newer GTK" redistributable from?  I could not find one available for download (see my comment above)

**Comment by alexolog** [comment]
But I am also concerned that smileys don't seem to work either

**Comment by szr8** [comment]
On 11/19/2019 9:45 AM, Alex wrote:
>
> Where do I get a "newer GTK" redistributable from? I could not find 
> one available for download (see my comment above)
>

This will probably be your best bet:

https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

You'll want to choose the gtk2 installer 
(gtk2-runtime-2.24.32-2019-11-07-ts-win64.exe is presently the latest 
release.)

**Comment by alexolog** [comment]
As far as I know, Pidgin on Windows is a 32-bit application that uses 32-bit DLLs.

**Comment by alexolog** [comment]
2.14 was supposed to fix the emoji issue but I see the same behaviour.

**Comment by EionRobb** [comment]
@alexolog the fix in 2.14 was to let emoji smiley themes work, eg with https://github.com/nobuyukinyuu/pidgin-emoji or https://github.com/saltire/android-emoji-pidgin

If you want built-in support without an emoji them, then upgrading to a newer GTK+ version is the only option

**Comment by alexolog** [comment]
Using an emoji theme now woks
