### ISSUE TITLE
Smileys are not replaced by emojis

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#259]
If I type :) in the native client, it gets replaced with an emoji.
If I do that in Pidgin, the smiley is sent verbatim.

**Comment by bobbybee** [comment]
This is a client issue, not a prpl issue -- in this case, it's a missing feature in Pidgin.

Non-Pidgin clients using purple-discord do replace emoticons to emojis.

**Comment by alexolog** [comment]
Is there a chance it will be fixed in Pidgin?

**Comment by EionRobb** [comment]
You can use the Text Replacement plugin in Pidgin to change `:)` into 🙂

**Comment by alexolog** [comment]
The Discord client changes :) to :slight_smile: not a Unicode glyph.
I suspect it will not work with other transports.
