### ISSUE TITLE
Tooltip info

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#26]
The status and in-game info isn't displaying in the tooltip for a buddy.  See issue #23

**Comment by EionRobb** [comment]
Fixed by https://github.com/EionRobb/purple-discord/commit/ca04d9b0ecda120756d4c3b2e1375fb1f4b14ef9

**Comment by EionRobb** [comment]
@Eloston hope that does the trick for you :)

**Comment by Eloston** [comment]
@EionRobb Thanks for the change, but unfortunately tooltips don't quite fit my use case. I don't have any friends on Discord, so I wanted to be able to view more info about someone by going to Conversation -> Get Info in a buddy chat window, or by right-clicking a username from a room member list and selecting Info (which I am guessing are the same dialog box, right?).

On a related note, I see that you hooked up adding a buddy to the friends request feature. Could there be an option to send a friend request separately from adding a buddy?
