### ISSUE TITLE
cppcheck: scope reduction: discord_blist_node_menu: act variable

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#261]
The act variable from the discord_blist_node_menu is only used when the channel variable is not NULL, so its scope can be reduced to the scope created by the not NULL check.

```
$ cppcheck -j1 --quiet --enable=all .
[libdiscord.c:5589]: (style) The scope of the variable 'act' can be reduced.
```

**Comment by EionRobb** [comment]
Thanks :)
