### ISSUE TITLE
use Unix line endings for libdiscord.c and Makefile

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#262]
I noticed that the libdiscord.c and Makefile files use Windows line endings (CRLF aka \r\n) while most of the other files in the repository use Unix line endings (LF aka \n).

In addition it seems that the [FreeBSD package has to workaround](https://svnweb.freebsd.org/ports/head/net-im/purple-discord/Makefile?view=markup) the Makefile using Windows line endings.

Please convert both libdiscord.c and Makefile to Unix line endings. Most software these days supports Unix line endings, I think even newer versions of Microsoft Notepad on Windows 10 support Unix line endings.

**Comment by EionRobb** [comment]
Huh, never knew line endings would be a problem in this day-and-age :)

Thanks :)
