### ISSUE TITLE
Makefile: install -D option portability on FreeBSD 

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#263]
I noticed that the FreeBSD folks [patch the Makefile to remove the -D option to install](https://svnweb.freebsd.org/ports/head/net-im/purple-discord/files/patch-Makefile?view=co). I think it would be good to change the Makefile to be portable to all make/install implementations.

Based on their patch it seems like just deleting the -D would work but testing it locally on Linux, I get install failures, so I think the %-locale-install target should use mkdir before install just like the install target does.

**Comment by EionRobb** [comment]
Nice find.  Hopefully this makes their life easier :)
