### ISSUE TITLE
cannot find -lpurple issue

### ISSUE THREAD

**Issue by samedamci** [EionRobb/purple-discord#265]
I trying compile purple-discord on openSUSE. but when I use make command:

```bash
cc -fPIC -O2 -g -pipe -Wall -std=c99 -DDISCORD_PLUGIN_VERSION='"0.9.2019.09.02.git.9380d86"' -DMARKDOWN_PIDGIN -DENABLE_NLS -DLOCALEDIR=\"/usr/share/locale\"  -shared -o libdiscord.so libdiscord.c markdown.c -Wl,-z,relro `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`   -Ipurple2compat -g -ggdb
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: cannot find -lpurple
collect2: error: ld returned 1 exit status
make: *** [Makefile:108: libdiscord.so] Error 1
```

What is bad?

**Comment by EionRobb** [comment]
Sounds like you're missing libpurple.so?  Seems odd.  What does `pkg-config purple --libs --cflags` output?

**Comment by samedamci** [comment]
`-I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -lpurple -lglib-2.0`

**Comment by EionRobb** [comment]
That's really weird that it's not providing any `-L` path to where libpurple.so lives, eg `-L/usr/lib64/`, also concerning that it's not providing the `-ljson-glib-1.0`

What package manager commands did you use to install [the deps](https://github.com/EionRobb/purple-discord#compiling) for the plugin (libglib2.0-dev, libjson-glib-dev and libpurple-dev)

**Comment by samedamci** [comment]
I'm installed it via YaST Software.
