### ISSUE TITLE
Some channels are not auto-created

### ISSUE THREAD

**Issue by zevelorgani** [EionRobb/purple-discord#268]
There are channels on some servers that are only visible to members with certain roles, but even though I have those roles, and the native discord client shows me all the channels, Pidgin only populates some of them but not others.

The message from the debug log is on https://pastebin.com/6Fkass0v
More information is on https://pastebin.com/n9Mh8nkP
Please note that it is a NSFW server, but it is the only one I am registered on that exhibits this behavior.  I put the actual data on pastebin just to be sure.

**Comment by EionRobb** [comment]
I've been doing a bit of work on this lately, are you using the latest version from git or the latest release?

**Comment by EionRobb** [comment]
Ok, for the dorse channel, there's two roles that you're in that play a part 'mild' is blocked, 'extreme' is allowed

When we're saving the roles assigned to a channel, we do it back-to-front, so that it's checking extreme first then mild, so shows you as being blocked.

We just need to reverse this ordering, but I need to double-check why it was done backwards in the first place

**Comment by EionRobb** [comment]
Whoops, not quite right, its the user's roles that we store back to front: https://github.com/EionRobb/purple-discord/blob/master/libdiscord.c#L2780-L2783

**Comment by EionRobb** [comment]
Can you try with https://github.com/EionRobb/purple-discord/commit/909109c2de2baccae800d86455940e8c10207d58 to see if that resolves?

**Comment by zevelorgani** [comment]
Do you have a Windows DLL I can try?

**Comment by EionRobb** [comment]
Whoops, sorry, should have asked what OS you're on. 
There's builds based on the latest commits at https://eion.robbmob.com/libdiscord.dll

**Comment by zevelorgani** [comment]
Seems to be working fine.  Thank you!

**Comment by EionRobb** [comment]
Yay! Good stuff. Thanks for coming back to say that it's working :)
