### ISSUE TITLE
Add "Get Info" for users

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#27]
@Eloston would like to have the option to "Get Info" on users who aren't in the contact list to be able to see their online status and what game they're playing.  See issue #26

**Comment by Eloston** [comment]
Is there only one "Get Info" dialog box? i.e. is the option from the member list of a channel and the option from a direct message window the same option? If they are, then we'll need some other interface for the second idea of #23.

**Comment by EionRobb** [comment]
Yeah, there's only one "Get Info".  I've created one using all the info we get from the "Profile" API in Discord, but unfortunately I can't get it to display online/game status info until @p4plus2 works his magic first.

**Comment by Eloston** [comment]
Okay, sounds good. 

> but unfortunately I can't get it to display online/game status info until @p4plus2 works his magic first.

You mean there's some undocumented API we will need to use?

**Comment by EionRobb** [comment]
There we go, should have status info in the Get Info popups now :)
![image](https://cloud.githubusercontent.com/assets/1063865/26022362/f06d271c-37f7-11e7-9c6e-50493dfdd5a1.png)

**Comment by Eloston** [comment]
Nice, thanks. Perhaps we can close this now?

**Comment by EionRobb** [comment]
Have you tried it out? Does it work ok?

**Comment by Eloston** [comment]
Oh yeah, it works great.

**Comment by EionRobb** [comment]
:)
