### ISSUE TITLE
clang scan-build reports "Dead nested assignment" & "Memory leak"

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#271]
With the latest git master, LLVM's `scan-build make -j4` reports a couple of warnings:

```
libdiscord.c:4261:29: warning: Although the value stored to 'read_len' is used in the enclosing expression, the value is never actually read from 'read_len'
                while (nlbr_count < 4 && (read_len = purple_ssl_read(conn, &nextchar, 1)) == 1) {
                                          ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libdiscord.c:5556:4: warning: Potential leak of memory pointed to by 'msg'
                        g_free(postdata);
                        ^~~~~~~~~~~~~~~~
```

**Comment by pabs3** [comment]
Please note that the first warning is only shown with LLVM 10.

**Comment by EionRobb** [comment]
Is there any comment or anything that can be added to disable the warning for the potential leak of memory?  This is a false positive (it's `free`'d in the purple_message_destroy in the callback in `discord_created_direct_message_send()`)

**Comment by EionRobb** [comment]
Actually, the first one looks like a false-positive to me too?  The `read_len` is used later on down the function?

**Comment by pabs3** [comment]
Looking at the code there are situations where the callback will not be
called by `discord_fetch_url_with_method` (for example it returns early
when the account is not connected) so I think that it would be best to
free msg in the function it was allocated in too, but please make sure
to avoid freeing it twice by setting it to NULL after freeing it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
The `read_len` value used later on comes from another assignment of
`read_len` in a second similar loop expression but further down outside
of the G_UNLIKELY condition. The `read_len` value assigned in the first
loop is never used before the second loop.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
This is now fixed, thanks!
