### ISSUE TITLE
Make install error

### ISSUE THREAD

**Issue by entryb** [EionRobb/purple-discord#276]
The plugin compiles without error but something seems wrong with make install routines:
convert-im6.q16: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1919.
convert-im6.q16: unable to open file `/tmp/magick-17889dEkzyCdcXKT8': No such file or directory @ error/constitute.c/ReadImage/544.
convert-im6.q16: no images defined `discord16.png' @ error/convert.c/ConvertImageCommand/3258.
Makefile:138: recipe for target 'discord16.png' failed
make: *** [discord16.png] Error 1

**Comment by EionRobb** [comment]
Ugh, I hate that part of the Makefile and I want to get rid of it (something to do with repeatable builds and not including 'compiled' output in your source tree).  For now you can download the images from `https://eion.robbmob.com/discord16.png`, `https://eion.robbmob.com/discord32.png` and `https://eion.robbmob.com/discord48.png` - they're just the protocol icons to show up in Pidgin, completely optional
