### ISSUE TITLE
Status messages are shown as "playing"

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#279]
Discord is supporting custom status messages.
My contacts are confused about my status being shown as "Playing <status>"

**Comment by EionRobb** [comment]
What do you have set for the "Use status message as in-game info" flag?

I'll update the docs but basically:
* If that setting is enabled, then your Discord status message will be an "in game .... " message
* If that setting is disabled, then your Discord custom status message will be set to the message you set

Kinda weird that it would say "Playing " without anything else afterwards.  What do you have your status set to in Pidgin?

**Comment by alexolog** [comment]
There was more text after the "playing" but markdown ate it.

Thanks, I'll check the setting.  I thought it had a different meaning before.

**Comment by alexolog** [comment]
Works.  Closing.
