### ISSUE TITLE
Add option for opening channel group chat on incoming messages (small groups)

### ISSUE THREAD

**Issue by leso-KN** [EionRobb/purple-discord#28]
It would be nice to have an option to open a group chat window when a message was received.

I noticed the group contact is being highlighted once there are new messages, but no window pops up. That's good for big channels.
However for small groups, i'd find it cool if the chat window would popup on incoming messages.

Maybe add some kind of checkbox to the group chat settings to toggle that feature at will?

**Comment by bobbybee** [comment]
Essentially the same as #22, please keep discussion in one place.
