### ISSUE TITLE
Feature Request: Buddy Protocol icons

### ISSUE THREAD

**Issue by discorduserrequest** [EionRobb/purple-discord#282]
Thanks for making this - it's an awesome tool.  Would it be possible to add a Discord protocol icon for the buddy list and account?  It would make it much easier to tell account I'm sending over at a glance.

**Comment by EionRobb** [comment]
I'm assuming that you're a Windows user (as the plugin ships/builds with protocol icons)?

You can copy the icons from https://github.com/EionRobb/purple-discord/raw/5f2af64501850a60b9b4ef3673e8b12e751353c0/discord16.png https://github.com/EionRobb/purple-discord/raw/5f2af64501850a60b9b4ef3673e8b12e751353c0/discord22.png and https://github.com/EionRobb/purple-discord/raw/5f2af64501850a60b9b4ef3673e8b12e751353c0/discord48.png into your C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols folder
