### ISSUE TITLE
null#0000 roomlist

### ISSUE THREAD

**Issue by fmlatghor** [EionRobb/purple-discord#286]
Pidgin shows non-friendlist username as `null#0000` when that person is offline and sends a message for the first time.

**Comment by EionRobb** [comment]
Can you get a debug log when it happens next? What version of the plugin are you using?

**Comment by fmlatghor** [comment]
I'm running the latest. I'll try to get a debug log when this happens again.
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 14, 2020, 17:38 by notifications@github.com:

**Comment by EionRobb** [comment]
Just to confirm, you've just compiled from git, or using the pre built dll from a couple of days ago?

**Comment by fmlatghor** [comment]
Dnf package
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 14, 2020, 17:55 by notifications@github.com:

**Comment by EionRobb** [comment]
Ah. Might not be new enough
