### ISSUE TITLE
crash in ssl_gnutls_read

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#290]
This was probably with the previous build.  I am getting the crash on windows and linux didn't build pidgin from source on windows but here is the backtrace from finch

gdb finch

#0  0x00007fffe87a815c in ssl_gnutls_read (gsc=0x555555664000, data=0x5555559cf520, len=1) at ssl-gnutls.c:456
#1  0x00007fffeafa3aa1 in discord_socket_got_data (userdata=0x5555559cf4b0, conn=0x555555664000, cond=<optimized out>)
    at libdiscord.c:3564
#2  0x000055555557e0e2 in purple_gnt_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x555555a302a0)
    at finch.c:181
#3  0x00007ffff768062d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff7680aa0 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007ffff7681082 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#6  0x0000555555569454 in main (argc=1, argv=0x7fffffffdc58) at finch.c:457
(gdb) 

_Originally posted by @klikevil in https://github.com/EionRobb/purple-discord/issues/288#issuecomment-613102471_

**Comment by EionRobb** [comment]
@klikevil can you attach a debug log from before the crash?

**Comment by klikevil** [comment]
Well it's crashing on windows too even with the new build, but I don't think it crashes in libdiscord anymore using the most recent pidgin, if i have the debug window open will it continually write to the file i save it as up until the crash?  Because I can no longer interact with pidgin/finch up to the crash point, if you want on my linux server I can recompile pidgin without optimization to try to get you a better spot that it is crashing at so the code won't be optimized out.

**Comment by EionRobb** [comment]
You'll need to get the debug log from command line with the --debug flag 

If it's crashing on windows, can you provide the %appdata%\.purple\Pidgin.RPT file

**Comment by EionRobb** [comment]
Any update on the debug log before the crash?

**Comment by klikevil** [comment]
Thanks will get back to you :D

**Comment by klikevil** [comment]
Unhandled exception at 0x6A6B21D2 (ssl-nss.dll) in pidgin.exe: 0xC0000005: Access violation reading location 0x00000004.

**Comment by klikevil** [comment]
![image](https://user-images.githubusercontent.com/32278206/79639356-6b455600-8159-11ea-833f-49e3fb2b11b9.png)

Launching with debug flag will get back to you next crash, sorry that took so long been busy

**Comment by klikevil** [comment]
[pidgin.zip](https://github.com/EionRobb/purple-discord/files/4497085/pidgin.zip)
Here is the debug log

**Comment by EionRobb** [comment]
Thanks for attaching the crash log.  Could you also attach a debug log from when you run pidgin with the --debug flag? https://developer.pidgin.im/wiki/TipsForBugReports#ObtainingaDebugLog

**Comment by klikevil** [comment]
Thanks for that, here is the requested file.
[pidgin-debug-log-output.zip](https://github.com/EionRobb/purple-discord/files/4498786/pidgin-debug-log-output.zip)

**Comment by hoehermann** [comment]
With 8fe9dc, I observe

    (22:46:32) discord: sending frame: {"op":1,"d":59}
    (22:46:32) discord: got frame data: {"t":null,"s":null,"op":11,"d":null}

repeated around every, for hours. Then once

    (22:46:53) discord: got frame data: {"t":null,"s":null,"op":7,"d":null}
    (22:46:53) dnsquery: Performing DNS lookup for gateway.discord.gg

and the crash occurs with a stack-trace like the above.

PS: This is the first time in weeks the crash happened while I was logging the debug output. Quite elusive, this one. ;)

**Comment by EionRobb** [comment]
@hoehermann do you have the backtrace from your crash as there's a couple of different backtraces 'above' :)

**Comment by hoehermann** [comment]
Dang it. No, I do not have the backtrace. -.-

It seems like I either remember to keep the debug output or have apport enabled. – Never both.

It is usually

    #0  0x… in  () at /usr/lib/purple-2/ssl-nss.so
    #1  0x… in discord_socket_got_data (userdata=0x55dc721610e0, conn=0x55dc7215e8e0, cond=<optimized out>) at libdiscord.c:3589

**Comment by klikevil** [comment]
here is another one from the linux version in finch again with the finch debug log.

```
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from finch...
Reading symbols from /usr/lib64/debug//usr/bin/finch.debug...
[New LWP 17708]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `finch --debug'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f880441c15c in ssl_gnutls_read (gsc=0x7f88140bd140, data=0x7f88140b6470, len=1) at ssl-gnutls.c:456
456     ssl-gnutls.c: No such file or directory.
(gdb) bt
#0  0x00007f880441c15c in ssl_gnutls_read (gsc=0x7f88140bd140, data=0x7f88140b6470, len=1) at ssl-gnutls.c:456
#1  0x00007f8806c24aa1 in discord_socket_got_data (userdata=0x7f88140b6400, conn=0x7f88140bd140, cond=<optimized out>)
    at libdiscord.c:3564
#2  0x00007f88134b00e2 in purple_gnt_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x7f8814194bd0)
    at finch.c:181
#3  0x00007f8812b0762d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f8812b07aa0 in ?? () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f8812b08082 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#6  0x00007f881349b454 in main (argc=2, argv=0x7ffd7114ac68) at finch.c:457
(gdb) 
[finch-debug.log](https://github.com/EionRobb/purple-discord/files/4755556/finch-debug.log)

```

**Comment by EionRobb** [comment]
@klikevil can you rebuild the plugin from git?  Line 3564 doesn't line up with the crash any more

**Comment by klikevil** [comment]
Woah the one from git actually shows what channels I am in!

**Comment by br4nnigan** [comment]
I'm also getting this error. Makes pidgin crash after some time, basically daily.

I'm using pidgin 2.12 for compatibility reasons

my pidgin.RPT starts at April 3 and it's always this one error. I don't know what changed then, maybe I joined another server?

I will use --debug flag now...

```
Error occured on Friday, April 3, 2020 at 10:30:15.

Windows Version 6.1 Build 7601 Service Pack 1

E:\Pidgin\pidgin.exe caused an Access Violation at location 703e21d2 in module E:\Pidgin\plugins\ssl-nss.dll Reading from location 00000004.

Registers:
eax=00000000 ebx=00000000 ecx=00000001 edx=0277f700 esi=00000000 edi=734e2b04
eip=703e21d2 esp=0028ecf0 ebp=0028ede8 iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246

Call stack:
         Using Debug Symbols from: E:\Pidgin\pidgin-2.12.0-dbgsym\plugins\ssl-nss.dll.dbgsym
703E21D2 E:\Pidgin\plugins\ssl-nss.dll
         E:\Pidgin\pidgin.dll [2.12.0.0]
         Using Debug Symbols from: E:\Pidgin\pidgin-2.12.0-dbgsym\pidgin.dll.dbgsym
73ABFA48 E:\Pidgin\pidgin.dll  pidgin_docklet_uninit
         E:\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
685EB90D E:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EBD9D E:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
         E:\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
022D4260 E:\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main
```

**Comment by EionRobb** [comment]
@br4nnigan if the 'compatibility reasons' are to do with emoji, then we've fixed that in Pidgin 2.14 :)
We've also fixed the cause of this crash in 2.14, so anyone still experiencing this should upgrade

**Comment by alexolog** [comment]
> @br4nnigan if the 'compatibility reasons' are to do with emoji, then we've fixed that in Pidgin 2.14 
I installed 2.14.1 and still see emoji as tofu.  What am I missing?

**Comment by br4nnigan** [comment]
@EionRobb  yeah I think it was because smileys!

@alexolog I have set Apple Emoji Theme by Steffen Vogel as "smiley theme" and it works. Maybe that helps?

**Comment by alexolog** [comment]
An emoji theme works.  Thank you.
