### ISSUE TITLE
says 0 users in room

### ISSUE THREAD

**Issue by Svetlana-T** [EionRobb/purple-discord#291]
While discord web app lists three online users and about six offline users. In pidgin it says 0 users in the room. Tried restarting Pidgin, still the same issue. Using debian stable and the respective latest stable packages for it.

**Comment by EionRobb** [comment]
See issue #283 

You'll need to update to a version built from the latest git

**Comment by Svetlana-T** [comment]
Thank you, Is the newer version packaged for debian as a third-party repository or in debian backports?

**Comment by EionRobb** [comment]
See issue #289 for that one :)

**Comment by Svetlana-T** [comment]
Thank you EionRobb. The backports version shows the users who are currently online now. This is an improvement (:

Is there a way to see users who are in the current room, but currently offline? Discord web app shows this.
