### ISSUE TITLE
ld: unknown option: -z on OSX

### ISSUE THREAD

**Issue by fizzy123** [EionRobb/purple-discord#294]
Running `make` results in 
```
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I applied this fix: https://github.com/rbsec/sslscan/issues/137 on my local machine and that worked. not sure if that's what yall wanna do, but it's an option.

macOs Version 10.15.4
```
clang --version
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

**Comment by EionRobb** [comment]
Hopefully that commit helps? :)
