### ISSUE TITLE
Disconnect with message "The action attempted has been deemed abusive"

### ISSUE THREAD

**Issue by aidaho** [EionRobb/purple-discord#295]
Hi.

I'm using purple-discord from debian backports (0.9.2020.04.05.git.db7dc79-1~bpo10+1) on Pidgin 2.13.0 (libpurple 2.13.0)  

Recently I've been getting constantly idle-disconnected with the message
"The action attempted has been deemed abusive or is otherwise disallowed".  
I've tried logging out other computers, just in case I'm tripping some request rate limit, but this does not help.  

Attached is a pidgin debug log excerpt with failed request to graph.facebook.com

[purple-debug.log](https://github.com/EionRobb/purple-discord/files/4708003/purple-debug.log)

**Comment by alexolog** [comment]
Facebook, not Discord.
Try here: https://github.com/dequis/purple-facebook/issues/486

**Comment by aidaho** [comment]
Ouch, my bad. Had two tabs next to each other. Closing.
