### ISSUE TITLE
Attachments not being displayed (and neither is its link to the discord cloud)

### ISSUE THREAD

**Issue by rdvl97** [EionRobb/purple-discord#3]
![image](https://cloud.githubusercontent.com/assets/3316274/25117421/f3c7a06c-23c6-11e7-8fbb-34fd4f1a8d81.png)
You should be able to get away with just grabbing the link to the image and putting it in it's place (cdn.discordapp.com/attachments/)

**Comment by EionRobb** [comment]
:)

**Comment by EionRobb** [comment]
Should be working

**Comment by rdvl97** [comment]
yup, works now
