### ISSUE TITLE
Can't seem to build in ubuntu 18

### ISSUE THREAD

**Issue by DuendeInexistente** [EionRobb/purple-discord#304]
I'm trying to make a new build in ubuntu 18, I compiled it in this machine before (My local repo was at 4b3d620 before pulling) so all the library stuff should be in order. Maybe something to do with those four changes to Makefile git reported?

**Comment by EionRobb** [comment]
Can you attach the log from compiling?  Tricky to see what's going wrong without seeing whats going wrong :)

**Comment by DuendeInexistente** [comment]
How the hell did I forget to do that?
It's not detecting libpurple. All libraries are up to date.
> echo "You need libpurple development headers installed to be able to compile this plugin"
>
> You need libpurple development headers installed to be able to compile this plugin

**Comment by EionRobb** [comment]
What does `pkg-config purple --libs --cflags` output?

**Comment by EionRobb** [comment]
It might be that you're missing the libpurple-dev package, but have the libpurple package installed instead?

**Comment by DuendeInexistente** [comment]
Libpurple-dev is installed, but it seems to go under some other name in pkg config. 
```
┌─[cammera@SafeHavensDock]─[~/SoftwareBuilds/purple-discor2]git:(master)
└─➤ sudo apt install libpurple-dev                                          1 ↵
[sudo] password for cammera: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpurple-dev is already the newest version (1:2.12.0-1ubuntu4).
The following packages were automatically installed and are no longer required:
  golang-1.10-go golang-1.10-src golang-src libllvm8 linux-headers-4.15.0-64
  linux-headers-4.15.0-64-generic linux-image-4.15.0-64-generic
  linux-modules-4.15.0-64-generic linux-modules-extra-4.15.0-64-generic
  phantomjs python3-pyxattr rtmpdump
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
┌─[cammera@SafeHavensDock]─[~/SoftwareBuilds/purple-discor2]git:(master)
└─➤ pkg-config libpurple-dev purple purple-dev libpurple --libs --cflags  100 ↵
Package libpurple-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpurple-dev.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpurple-dev' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple-dev was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple-dev.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple-dev' found
Package libpurple was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpurple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpurple' found
         ```

**Comment by EionRobb** [comment]
Hmm... how about `pkg-config purple-2` or `purple2`?  Is there a `purple.pc` file in /usr/lib/x86_64-linux-gnu/pkgconfig or /usr/lib/pkgconfig or somewhere else in the pkg-config search path?

I've just checked on my Ubuntu 18 machine and the purple.pc is hiding in there and seems to be ok

```
eion@lexi:~$ ls /usr/lib/x86_64-linux-gnu/pkgconfig/purple*
/usr/lib/x86_64-linux-gnu/pkgconfig/purple.pc
eion@lexi:~$ pkg-config purple --cflags --libs
-I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lpurple -lglib-2.0
eion@lexi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by DuendeInexistente** [comment]
*God damn it*, third computer where this happens to me and it still took me by surprise.
Homebrew had taken over pkg-config at some point, no idea when and of course making it completely ignore system dev libraries and giving you notice of it.
Totally homebrew fault on this one. And mine for forgetting about that.

**Comment by EionRobb** [comment]
Phew, `apt` is three too many package managers for me, and you've got twice that many? :)

Glad to hear you've sorted it :+1:

**Comment by DuendeInexistente** [comment]
[Living la vida loca.](https://xkcd.com/1654/)
