### ISSUE TITLE
Server icon on taskbar and buddy list.

### ISSUE THREAD

**Issue by MangaD** [EionRobb/purple-discord#307]
I love that avatars show on the buddy list and taskbar, but this doesn't happen for channels. Would it be possible to show the server icon on these?

**Comment by EionRobb** [comment]
Sadly the libpurple API doesn't have the ability to add an icon for group chats, so this isn't possible :(

**Comment by MangaD** [comment]
Have you considered opening an issue at libpurple for it to provide this feature?

**Comment by EionRobb** [comment]
Pidgin 2 is not getting any new features. Pidgin 3 is still being worked on, but I'm not going to add support until the api is stable
