### ISSUE TITLE
chat history?

### ISSUE THREAD

**Issue by TRPB** [EionRobb/purple-discord#319]
According to #194 this plugin downloads the chat history on startup. Do I need to manually enable this feature somewhere as no history at all is showing for me.

**Comment by johndoe71rus** [comment]
Do you enable logging? 
 preferences ->  logging

**Comment by mattdawolf** [comment]
> Do you enable logging?
> preferences -> logging
> and enable plugin history

Using Pidgin 2.14.3. Not finding "enable plugin history" in the logging section of preferences.

**Comment by EionRobb** [comment]
> > Do you enable logging?
> > preferences -> logging
> > and enable plugin history
> 
> Using Pidgin 2.14.3. Not finding "enable plugin history" in the logging section of preferences.

I think they mean enabling the History plugin through  Tools->Plugins->History
