### ISSUE TITLE
Cannot compile purple discord

### ISSUE THREAD

**Issue by asdfghjkl403622** [EionRobb/purple-discord#320]
Hello!
I am running on raspbian 64 bit, and was trying to compile purple discord, and after using the make command I encountered this error:
`cc -fPIC -O2 -g -pipe -Wall -std=c99 -DDISCORD_PLUGIN_VERSION='"0.9.2021.01.18.git.8216905"' -DMARKDOWN_PIDGIN -DENABLE_NLS -DLOCALEDIR=\"/usr/share/locale\"  -shared -o libdiscord.so libdiscord.c markdown.c -Wl,-z,relro `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`   -Ipurple2compat -g -ggdb
Package json-glib-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-glib-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-glib-1.0' found
libdiscord.c:36:16: fatal error: glib/gi18n-lib.h: No such file or directory
 #      include <glib/gi18n-lib.h>
                ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from markdown.c:20:
markdown.h:23:10: fatal error: purple.h: No such file or directory
 #include <purple.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:108: libdiscord.so] Error 1
`
I do not know what to do here, and I am newer to Linux so simple explanations are preferred.

**Comment by EionRobb** [comment]
It looks like you're missing the dependencies.

Can you install the dev packages that are mentioned at https://github.com/EionRobb/purple-discord#compiling in your package manager?

**Comment by asdfghjkl403622** [comment]
it seems to have compiled without errors! now if you do not mind me asking, what do I do from here? I have it compiled in my home directory.

**Comment by EionRobb** [comment]
The `sudo make install` line should have added it to your system's Pidgin.  Once you restart Pidgin then Discord should show in the Protocols dropdown list when you add a new account

**Comment by asdfghjkl403622** [comment]
Thank you so much! I wanted an application for discord instead of using the bloated browser, and this did the trick!

**Comment by EionRobb** [comment]
👍
