### ISSUE TITLE
compilation error Ubuntu 20.04

### ISSUE THREAD

**Issue by chuckis** [EionRobb/purple-discord#322]
got error:
uk@inspiron:~/purple-discord$ make
cc -fPIC -O2 -g -pipe -Wall -std=c99 -DDISCORD_PLUGIN_VERSION='"0.9.2021.02.09.git.2ed0a30"' -DMARKDOWN_PIDGIN -DENABLE_NLS -DLOCALEDIR=\"/usr/share/locale\"  -shared -o libdiscord.so libdiscord.c markdown.c -Wl,-z,relro `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`   -Ipurple2compat -g -ggdb
Package json-glib-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-glib-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-glib-1.0' found
libdiscord.c:36:16: fatal error: glib/gi18n-lib.h: Нет такого файла или каталога
   36 | #      include <glib/gi18n-lib.h>
      |                ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from markdown.c:20:
markdown.h:23:10: fatal error: purple.h: Нет такого файла или каталога
   23 | #include <purple.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:108: libdiscord.so]

**Comment by EionRobb** [comment]
As per https://github.com/EionRobb/purple-discord#compiling you'll need "devel headers/libs for libpurple and libjson-glib [libglib2.0-dev, libjson-glib-dev and libpurple-dev], as well as ImageMagick [imagemagick] and [gettext]."
