### ISSUE TITLE
Discord not showing up in "add account" window

### ISSUE THREAD

**Issue by qpinewasalreadytaken** [EionRobb/purple-discord#323]
Hi there, I'm using a virtual machine installation of Windows XP just for fun, and decided to install Pidgin. I was also incredibly excited to find a Discord plugin, so I really have to say thank you for the nostalgia overload!
However, when I start up Pidgin, Discord doesn't show up under the list of protocols. Do I have to do anything for the Advanced tab like changing the server or port? Whatever help you can offer will be highly appreciated. 😃

**Comment by EionRobb** [comment]
Just to check, did you install the libjson-glib.dll into the Program Files\Pidgin folder (not in the plugins dir)?

If so, then can you get a debug log of loading the plugins list:  Open the debug log (Help->Debug Window) then leave that open and open the plugins list (Tools->Plugins) then close the plugins list, and copy-paste the output of the debug window

**Comment by qpinewasalreadytaken** [comment]
Oh never mind, I figured it out. Had the libdiscord.dll file in the Program Files\Pidgin rather than %APPDATA%\.purple\plugins, LOL! 
Thank you for the help anyways!
