### ISSUE TITLE
common crash regarding file sharing with the discord plugin

### ISSUE THREAD

**Issue by arsongoetia** [EionRobb/purple-discord#324]
very frequently, after hitting insert to upload an image, if I hit backspace to clear said image, pidgin will hang and then crash. 

-------------------

Error occured on Thursday, February 18, 2021 at 04:34:24.

Windows Version 6.2 Build 9200 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 61839732 in module C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll Reading from location aaaaaaab.

Registers:
eax=02731f10 ebx=1076b750 ecx=5cfe2cdf edx=aaaaaaab esi=04f46970 edi=00000004
eip=61839732 esp=0061c130 ebp=0061c158 iopl=0         nv up ei ng nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210282

Call stack:
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
61839732 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_image_set_from_pixbuf
         C:\Program Files (x86)\Pidgin\pidgin.dll [2.14.1.0]
6DBE4ED8 C:\Program Files (x86)\Pidgin\pidgin.dll  gtk_imhtml_image_scale
6DBEB9C7 C:\Program Files (x86)\Pidgin\pidgin.dll  gtk_imhtml_scroll_to_end
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
618BA4E1 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_scrolled_window_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
61819526 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_frame_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6187BB86 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_notebook_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6197DAB4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_window_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
617CEE54 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_resize_children
6197DCE9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_window_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54512 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
617CEEC5 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_check_resize
617CF192 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_check_resize
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll [2.16.6.0]
6C3414C0 C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll  gdk_threads_add_timeout_seconds
         C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
685EB167 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EB90D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EBD9D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
61854260 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main

-------------------

Error occured on Sunday, February 21, 2021 at 18:14:48.

Windows Version 6.2 Build 9200 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 61839732 in module C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll Reading from location aaaaaaab.

Registers:
eax=0273b600 ebx=052e05b0 ecx=1d53dd81 edx=aaaaaaab esi=0534e698 edi=00000004
eip=61839732 esp=0061c130 ebp=0061c158 iopl=0         nv up ei ng nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010282

Call stack:
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
61839732 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_image_set_from_pixbuf
         C:\Program Files (x86)\Pidgin\pidgin.dll [2.14.1.0]
         Using Debug Symbols from: C:\Program Files (x86)\Pidgin\pidgin-2.14.1-dbgsym\pidgin.dll.dbgsym
5ADE4ED8 C:\Program Files (x86)\Pidgin\pidgin.dll  gtk_imhtml_image_scale
5ADEB9C7 C:\Program Files (x86)\Pidgin\pidgin.dll  gtk_imhtml_scroll_to_end
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
618BA4E1 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_scrolled_window_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
61819526 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_frame_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6187BB86 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_notebook_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6179C219 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_box_pack_start_defaults
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A451F9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
6197DAB4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_window_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
6196B4B4 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_size_allocate
617CEE54 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_resize_children
6197DCE9 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_window_new
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54512 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
617CEEC5 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_check_resize
617CF192 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_check_resize
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll [2.16.6.0]
6C3414C0 C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll  gdk_threads_add_timeout_seconds
         C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
685EB167 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EB90D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EBD9D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
61854260 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main

**Comment by EionRobb** [comment]
Annoyingly, this is a bug in Pidgin that can't be fixed in the plugin :(
