### ISSUE TITLE
empty and missing messages

### ISSUE THREAD

**Issue by sebbu2** [EionRobb/purple-discord#328]
Since yesterday, i see empty EDIT, some EDIT with (null) messages, and there's some i don't even see at all. Most messages from others (if not all of them, i'm not sure), i don't see at all.
It makes the plugin not work at all, all i'm able to see are my own message and empty EDIT: lines.

**Comment by chainria** [comment]
Yeah same for me as well. I can only see my messages. Guess Discord changed something again. Can gladly provide debug logs if told what exactly to do. Hope this issue gets resolved quickly, since it completely breaks the plugin for me.

**Comment by Schmaiffe** [comment]
Yeah, whatever Discord changed completely broke the plugin for me too, I can see when people are online and I can send messages, but no messages sent to me get through. I primarily use it for DMs, so I haven't tested it in channels, but DMs to me don't work at all.

**Comment by Penaz91** [comment]
From a quick, late-night look at the debug logs, it seems the `MESSAGE_CREATE` events are captured by the plugin, but the "content" is always an empty string. Hope this helps.

**Comment by chainria** [comment]
> I primarily use it for DMs, so I haven't tested it in channels, but DMs to me don't work at all.

Welp, that rung my alarm bells. I ACTUALLY missed a lot of channel messages. But I can also pinpoint a quite exact time and date now, since I have a very busy channel (which actually annoys me usually, lol).

Last message in the channel was at 2021-04-27 12:04:15 MEST (GMT+2). Hope this helps. No messages after this date are visible in the logs (I haven't posted there as well).

**Comment by EionRobb** [comment]
Sorry for the missing messages. 

Can I just confirm whether anyone is having this issue with the very latest commits from master branch or if they're using a version that their distro is packaging?

**Comment by TearOfTheStar** [comment]
Using latest nightly on win10, same problem, I can send messages thru pidgin, but can't receive any.

**Comment by EionRobb** [comment]
Thanks for that. I thought I'd committed something recently that might have helped already but I thinkin got myself confused with the v8 api changes I've been working on instead

**Comment by chainria** [comment]
I am using a fairly new git version, from 2020-08-12. That should be @8fd7ceb89ea1f989f3a10569b218418e22c838ec. But I can update right now, no problem!

**Comment by EionRobb** [comment]
[libdiscord.zip](https://github.com/EionRobb/purple-discord/files/6408800/libdiscord.zip)
Can windows users try with this?

It looks like the cause is Discord doing another round of blocking "self bots", so rather than identify ourselves as "Pidgin" in the handshake with the discord servers, I'm telling them that we're a web browser, which seems to maybe have the desired effect.  Maybe.

**Comment by EionRobb** [comment]
(If you're compiling yourself, https://github.com/EionRobb/purple-discord/commit/02c88dbf8eb1bc9e3822149199e5149a2df08625 might be the commit that maybe fixes it)

**Comment by kecky** [comment]
I'm on windows and still run into this even with the newest nightly build. :(

**Comment by alexolog** [comment]
I am on Windows as well and haven't been affected.  Maybe it's a gradual rollout?
I don't think the DLL includes version information, does it?

**Comment by OrderlyUnicode** [comment]
It seems to not just be a Windows issue. I'm having the same problem with a fresh install on Arch.

**Comment by EionRobb** [comment]
Thanks for confirming the fix, @OrderlyUnicode :)

**Comment by alexolog** [comment]
So the new Windows DLL is good to install?

**Comment by kecky** [comment]
Still got the same issue even with the new build, sadly.

**Comment by chainria** [comment]
> Still got the same issue even with the new build, sadly.

Updated to 0.9.2021.05.01.git.beb44e8. Problem persists. However, now additionally not even a window pops up if I DM someone in Discord. And my messages are missing as well now. So basically, it's worse now :/

**Comment by chainria** [comment]
> I am on Windows as well and haven't been affected. Maybe it's a gradual rollout?
> I don't think the DLL includes version information, does it?

I took a look at the library and *DID* find version information. So I dug a little bit. You can find your version information unter Help > About Plugins. The order seems quite random, I have to scroll to the lower third of the list. Hope this helps!

**Comment by chainria** [comment]
> It seems to not just be a Windows issue. I'm having the same problem with a fresh install on Arch. Edit: Evidently, the version in the AUR is slightly out of date, so I'm going to try compiling it directly and see if that works.
> 
> Edit 2: Disregard all of this. compiling it myself fixed the issue for me.

Which version did you build? Since for me, everything got worse :P

**Comment by OrderlyUnicode** [comment]
> Which version did you build? Since for me, everything got worse :P

I installed it after the commit that was mentioned in a comment above. There's apparently been more commits since then, so maybe there was a regression?

**Comment by chainria** [comment]
> > Which version did you build? Since for me, everything got worse :P
> 
> I installed it after the commit that was mentioned in a comment above. There's apparently been more commits since then, so maybe there was a regression?

Thanks. Yeah, maybe. But not getting anything still looks better in the logs than only talking to myself. Actually, I might discard those later. So since it's completely broken now, I am open to any tests of upcoming commits :D

**Comment by EionRobb** [comment]
Ok, 5 more commits to make it more reliable.  Turns out there's a few more protocol changes during the initial handshake (I guess to reduce network traffic, although not by much since it's compressed anyway)

If self-compiling people can test with https://github.com/EionRobb/purple-discord/commit/c8be504eddf4523f814b6f9329f87bc4358fc9f6 and windows people with 
[libdiscord.zip](https://github.com/EionRobb/purple-discord/files/6409145/libdiscord.zip) that would be fantastic

**Comment by chainria** [comment]
> If self-compiling people can test with [c8be504](https://github.com/EionRobb/purple-discord/commit/c8be504eddf4523f814b6f9329f87bc4358fc9f6) and windows people with
> [libdiscord.zip](https://github.com/EionRobb/purple-discord/files/6409145/libdiscord.zip) that would be fantastic

Man... did they rewrite half of their protocol? Thanks for your fast help!

I can confirm 0.9.2021.05.01.git.c8be504 compiled under Gentoo working. DMing works, incoming and outgoing are shown and correctly transmitted between the two clients. So it doesn't matter where I respond, it works. Thank you!

**Comment by TearOfTheStar** [comment]
Yep, W10, working normally. Thank you!

**Comment by Schmaiffe** [comment]
Hi, sorry for late reply, I was also on Windows 10, and was at first using an old dll because I'm one of those problem users who doesn't update unless something is broken, then I tried the newest one (before my first comment) to see if that would fix it, but Discord's change was too new so no dice. Tried the dll in the zip and it works! I'm getting my DMs again, thank you.

**Comment by Tirus42** [comment]
I can also confirm that its works again. Tested under Debian Buster with the repo provided pidgin/libpurple version and the latest commit here (self build).

Thank you for your fast reaction and solution!

**Comment by alexolog** [comment]
> 
> 
> > I am on Windows as well and haven't been affected. Maybe it's a gradual rollout?
> > I don't think the DLL includes version information, does it?
> 
> I took a look at the library and _DID_ find version information. So I dug a little bit. You can find your version information under Help > About Plugins. The order seems quite random, I have to scroll to the lower third of the list. Hope this helps!

Thank you!

I am running:
Version: 0.9.2020.05.12.git.r672+.a791f12a4c73+

Seems to work still.

I will check the new zip in a moment

**Comment by alexolog** [comment]
> I will check the new zip in a moment

Seems to be working, but then the old one also worked for me

**Comment by LurkerHub** [comment]
Interestingly, the new version gets different JSON structures from Discord.

Specifically:
The old `"t":"READY"` JSON had  components that do not exist in the new one: `"presences"` and `"notes"`
The new one has 2 components that did not exist in the old: `"users"` and `"merged_members"`, as well as a new, separate `"t":"READY_SUPPLEMENTAL"` JSON.

In particular, the user's roles have moved from `d/guilds/members/roles` to `d/merged_members/roles`, which breaks the calculation of permissions.

I wonder if that could have caused #331

**Comment by Penaz91** [comment]
Seems that c8be504 solved the issue for me, I'm available for more tests if needed

**Comment by sebbu2** [comment]
It also solved the issue for me.

**Comment by alexolog** [comment]
Let's not close the issue until there's a working Windows DLL that implements the fix.
Not everybody compiles from source.

**Comment by Schmaiffe** [comment]
FWIW I didn't compile from source, I used the Windows DLL linked above, and it worked for me. I also just had someone test an edit with me (in a DM) and that worked too.

**Comment by EionRobb** [comment]
The nightly dll at https://eion.robbmob.com/libdiscord.dll has been updated with the changes mentioned in this issue
