### ISSUE TITLE
Unread flag not cleared. AT ALL.

### ISSUE THREAD

**Issue by chainria** [EionRobb/purple-discord#330]
As I (jokingly) wrote in #328 the unread flag didn't always get cleared. But since the new version, it doesn't seem to get cleared EVER. Which means Discord thinks there are unread messages everywhere. Doesn't really impact Purple/Pidgin really, but would be nice if this issue could be addressed. As always, I can gladly provide debug logs if told how to and also ready to test any commits.

Edit: Concerns DMs and Channels both.

**Comment by EionRobb** [comment]
Sorry about that, was trying to be too clever for my own good.  Should be fixed with the above commit.

**Comment by chainria** [comment]
Thank you very much! Confirmed working again in  873d859
