### ISSUE TITLE
Discord didn't receive message

### ISSUE THREAD

**Issue by disconnect00** [EionRobb/purple-discord#332]
Hi, since yesterday, I noticed that I couldn't receive message from both servers and DM via Discord. Meanwhile, I'm able to send message just fine. I've installed the new plugin, which steps should I take to fix it?

Thank you!

**Comment by chainria** [comment]
Take a look at #328 :)

**Comment by EionRobb** [comment]
Yep, dup of #328 - should be fixed by compiling a new copy of the plugin, or grabbing a new dll from https://eion.robbmob.com/libdiscord.dll :)

**Comment by disconnect00** [comment]
Thank you!
