### ISSUE TITLE
Nightly from May 02 crashes on startup

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#333]
Reverting to 0.9.2020.05.12.git.r672+.a791f12a4c73+ fixes the problem.

Log of 4 consecutive crashes, all on startup, all diferent:

-------------------

Error occured on Sunday, May 2, 2021 at 14:35:54.

Windows Version 10.0 Build 19042 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 68604463 in module C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll Reading from location 63d4208c.

Registers:
eax=00000001 ebx=00fbb888 ecx=00000019 edx=63d42088 esi=08f6f3a0 edi=00000001
eip=68604463 esp=0029df10 ebp=0029df68 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210202

Call stack:
68604463 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
68604704 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
686057B3 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slice_free1
685E7B4A C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_list_remove

-------------------

Error occured on Sunday, May 2, 2021 at 14:37:59.

Windows Version 10.0 Build 19042 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 6860454e in module C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll Writing to location 8bf70b0c.

Registers:
eax=0b5fc920 ebx=0b5fc918 ecx=11615230 edx=1177358f esi=77359800 edi=8bf70b08
eip=6860454e esp=007fe390 ebp=007fe3e8 iopl=0         nv up ei ng nz na pe cy
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210283

Call stack:
6860454E C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
68604704 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
68605B76 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slice_free_chain_with_offset
68605F65 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slist_free
6C35A7C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll  gdk_window_process_all_updates
6C35A823 C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll  gdk_window_process_all_updates
6C3414C0 C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll  gdk_threads_add_timeout_seconds
685EB167 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EB90D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EBD9D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
61854260 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main

-------------------

Error occured on Sunday, May 2, 2021 at 14:41:01.

Windows Version 10.0 Build 19042 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 6860454c in module C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll Reading from location 17c76000.

Registers:
eax=1017c6a8 ebx=1017c6a0 ecx=1164e848 edx=1017c777 esi=17c76000 edi=1017c5d8
eip=6860454c esp=0119fdd8 ebp=0119fe30 iopl=0         nv up ei ng nz ac pe cy
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010293

Call stack:
6860454C C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
686047CF C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
65C41B01 C:\Program Files (x86)\Pidgin\Gtk\bin\libgthread-2.0-0.dll
65C42055 C:\Program Files (x86)\Pidgin\Gtk\bin\libgthread-2.0-0.dll
766E6CFF C:\WINDOWS\System32\msvcrt.dll  beginthreadex
766E6DC1 C:\WINDOWS\System32\msvcrt.dll  endthreadex
76D4FA29 C:\WINDOWS\System32\KERNEL32.DLL  BaseThreadInitThunk
772C7A4E C:\WINDOWS\SYSTEM32\ntdll.dll  RtlGetAppContainerNamedObjectPath
772C7A1E C:\WINDOWS\SYSTEM32\ntdll.dll  RtlGetAppContainerNamedObjectPath

-------------------

Error occured on Sunday, May 2, 2021 at 14:43:12.

Windows Version 10.0 Build 19042 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 6860454c in module C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll Reading from location 14769800.

Registers:
eax=101475d8 ebx=101475d0 ecx=0b47d818 edx=1014768f esi=14769800 edi=014ab470
eip=6860454c esp=009fd5a0 ebp=009fd5f8 iopl=0         nv up ei ng nz na po cy
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210287

Call stack:
6860454C C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
68604704 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
686057B3 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slice_free1
68605F81 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slist_free_1
686061C1 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slist_remove
6186F3AB C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_misc_set_alignment
6186959C C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_menu_shell_get_take_focus
61844E05 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_item_get_type
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54512 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
61968F4F C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_is_composited
617CEDCE C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_forall
6196901C C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_is_composited
61869CEE C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_menu_shell_append
617CEDCE C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_forall
6196901C C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_is_composited
619690C5 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_is_composited
61973C13 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_unparent
617985D0 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_bin_get_child
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
617CF516 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_container_remove
6196ECF7 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_freeze_child_notify
63A4812F C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_object_run_dispose
61868E16 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_menu_item_new
63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
63A54D1F C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
6187FB48 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_object_destroy
63A4812F C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_object_run_dispose
6473EAA6 C:\Program Files (x86)\Pidgin\pidgin.dll  pidgin_blist_update_accounts_menu
6473F250 C:\Program Files (x86)\Pidgin\pidgin.dll  pidgin_blist_update_accounts_menu

**Comment by alexolog** [comment]
Why isn't there a link to a stable DLL?

**Comment by EionRobb** [comment]
That's weird. All those crashes are in Pidgin and not the plugin. Something to do with working out which flags in the command line have been passed through.

**Comment by EionRobb** [comment]
> Why isn't there a link to a stable DLL?

The nightly dll is stable, it's just nightly in name. Generally it's a dll that I've personally been using for a few minutes without issues and happy to let other people use, so it's not normally "unstable"

**Comment by alexolog** [comment]
The crashes started when I replaced the discord plugin with the "nightly" and stopped when I reverted to the one from #328 
I will try again

**Comment by alexolog** [comment]
w/o discord - works
with older discord DLL - works
with nightly, crashes (while parsing the blist?)

-------------------

Error occured on Sunday, May 2, 2021 at 16:27:58.

Windows Version 10.0 Build 19042 

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 6860454c in module C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll Reading from location 19959000.

Registers:
eax=0c1994d8 ebx=0c1994d0 ecx=11d31808 edx=0c1995a7 esi=19959000 edi=0bb898c8
eip=6860454c esp=011fe950 ebp=011fe9a8 iopl=0         nv up ei ng nz na po cy
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210287

Call stack:
6860454C C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
68604704 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_shell_parse_argv
686057B3 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slice_free1
68605F81 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slist_free_1
686061C1 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_slist_remove
6D128DEA C:\Program Files (x86)\Pidgin\libpurple.dll  xmlnode_get_next_twin
685EB22F C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EB90D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EBD9D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
61854260 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main

**Comment by alexolog** [comment]
The nightly does not work at all
The one from 328 is not usable because it bombards me with notifications

Suggestions?

**Comment by EionRobb** [comment]
Ok. I think I have maybe found a cause and fix. I managed to replicate the crash once out of 10 launches, so will do a new build and paste here shortly 

I think it's due to one of the hacks that I did to get the buddy list working again causing a double-free of memory

**Comment by LurkerHub** [comment]
Will any of these suggestions work under Windows to help track double-frees?
https://stackoverflow.com/questions/2902064/how-to-track-down-a-double-free-or-corruption-error

**Comment by alexolog** [comment]
Thanks Robb!  Eagerly waiting since reverting to 0.9.2020.05.12.git.r672+.a791f12a4c73+ no longer works

**Comment by EionRobb** [comment]
Ok, I think it's fixed with the change in https://github.com/EionRobb/purple-discord/commit/001dc28acea414d2a5e3dcf1c0563c61456ef17a#diff-2da497735529bb9402d0e9a974f7b1b928482a1129791f9823938f5449ad7e4fR2784

I've uploaded a new dll to https://eion.robbmob.com/libdiscord.dll if you want to try it

**Comment by LurkerHub** [comment]
Looks good!

**Comment by alexolog** [comment]
Thank you, this one works.
