### ISSUE TITLE
discord not pulling missed offline history

### ISSUE THREAD

**Issue by mattdawolf** [EionRobb/purple-discord#335]
I have pidgin 2.14.3 set as a daemon and autorespawning due to this [bug](https://issues.imfreedom.org/issue/PIDGIN-17441) so it is not frequent that this occurs to me. It is always reproducible if I say something in the cell version of Discord, and then bring pidgin online afterwards. No missed messages appear. I can state that when using Bionic Beaver, missed telegram and discord messages would appear as expected. I am using ubuntu 20.04.2 right now. 

Building from source vs package install made no difference. 

I do not know, if  any, link exists between telegram and discord missed messages not being pulled.

What would be useful for me to contribute? I assume I shall start with a backtrace?

**Comment by chainria** [comment]
The current fallout was a great test for this. While all my groups were synced fine, DM's were not. Which obviously is a great bummer because I wasn't online for a new days and these are missing from the history now.

**Comment by LurkerHub** [comment]
> The current fallout was a great test for this. While all my groups were synced fine, DM's were not. Which obviously is a great bummer because I wasn't online for a new days and these are missing from the history now.

@chainria, how did you manage to get the group synced?  Mine never do.

Also, #364 may be relevant

**Comment by chainria** [comment]
> @chainria, how did you manage to get the group synced? Mine never do.

Really, it just did magically. I started Pidgin and boom, there it was. I know it usally is a bit flakey, but it just worked.

**Comment by LurkerHub** [comment]
Hmmm...  Maybe auto-creating rooms has something to do with it?  Mine is set to off
