### ISSUE TITLE
static analysis: scan-build: memory leak in discord_send_im with purple 2

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#340]
scan-build reports a potential memory leak in discord_send_im with purple 2 with commit 414b63b (current master branch commit).

```
purple-discord (master=) $ scan-build make clean all V=1 clean
scan-build: Using '/usr/lib/llvm-11/bin/clang' for static analysis
rm -f libdiscord.so
rm -f discord*.png
/usr/share/clang/scan-build-11/bin/../libexec/ccc-analyzer -fPIC -O2 -g -pipe -Wall -std=c99 -DDISCORD_PLUGIN_VERSION='"0.9.2021.05.23.git.414b63b"' -DMARKDOWN_PIDGIN -DENABLE_NLS -DLOCALEDIR=\"/usr/share/locale\"  -shared -o libdiscord.so libdiscord.c markdown.c purple2compat/http.c purple2compat/purple-socket.c -Wl,-z,relro `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`   -Ipurple2compat -g -ggdb
libdiscord.c:6361:4: warning: Potential leak of memory pointed to by 'msg' [unix.Malloc]
                        g_free(postdata);
                        ^~~~~~~~~~~~~~~~
1 warning generated.
make: Nothing to be done for 'clean'.
scan-build: Analysis run complete.
scan-build: 1 bug found.
scan-build: Run 'scan-view /tmp/user/1000/scan-build-2021-05-23-084341-99891-1' to examine bug reports.
```

**Comment by pabs3** [comment]
The memory leak occurrs in the error path in `discord_send_im`, it needs this added:

```
#if !PURPLE_VERSION_CHECK(3, 0, 0)
                purple_message_destroy(msg);
#endif
```

**Comment by EionRobb** [comment]
Hmm... I think this is a false positive.  Won't the `discord_created_direct_message_send` callback destroy the `msg`?

**Comment by pabs3** [comment]
In most circumstances yes, but `discord_fetch_url_with_method_len`
doesn't call the callback when the connection is not valid or the
purple account is disconnected, so `msg` could leak if you try to send
a message on a disconnected account, not sure if that is possible.
Either way I think it is best to free `msg` in both places just to be
sure that no memory can leak from discord_send_im and also to silence
the scan-build warning so the output is more useful.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by EionRobb** [comment]
Except that adding that in will cause a double-free in the callback func :/ 

What if the request url func would always ensure the callback was called, even if just with null, instead?

**Comment by pabs3** [comment]
The double-free will only happen if msg isn't set to NULL after free.

Your suggestion sounds good, please do test if scan-build still
complains though and check the HTML report if it does.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by EionRobb** [comment]
That commit makes me a little nervous but seems to do the trick :)

**Comment by pabs3** [comment]
That commit introduced a new warning:

```
libdiscord.c:1127:3: warning: Called function pointer is null (null dereference) [core.CallAndMessage]
                callback(ya, NULL, user_data);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
OK, this looks fixed now, thanks!
