### ISSUE TITLE
Missed connection+SessionSave plugin makes SegFaults happen

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#35]
After the latest updates I can't manage to start Pidgin with purple-discord enabled, the program segfaults with the error I attached.
[log.zip](https://github.com/EionRobb/purple-discord/files/1000491/log.zip)

**Comment by EionRobb** [comment]
Can you attach a backtrace http://developer.pidgin.im/wiki/GetABacktrace

**Comment by Penaz91** [comment]
Seems that the segfault is provoked by the SessionSave plugin, but the plugin keeps losing connection to the server.
I can run the plugin without crashing pidgin, but it returns a "Lost connection to server"

**Comment by Penaz91** [comment]
Looks like now it connected, I'm really confused...

**Comment by EionRobb** [comment]
Yeah, strange. The logs showed that there was something interrupting the network connection too, but not sure what it could have been.

**Comment by Penaz91** [comment]
Changing the title to better suit what has happened

**Comment by EionRobb** [comment]
Are you able to get that backtrace, to be able to see what's crashing where?

**Comment by Penaz91** [comment]
I'm re-emerging pidgin with debug symbols enabled, can't speed up that, sorry ^-^''

**Comment by Penaz91** [comment]
I re-enabled the SessionSave plugin and Pidgin is not segfaulting anymore. I can't get the backtrace unless it starts crashing again, as soon as it does, I'll have a backtrace for you

**Comment by EionRobb** [comment]
try marking the account as offline, or disabling it and see if it crashes?

**Comment by Penaz91** [comment]
Marked the account as offline and we went down, here's the backtrace.
[pidgin-backtrace.zip](https://github.com/EionRobb/purple-discord/files/1000557/pidgin-backtrace.zip)

**Comment by EionRobb** [comment]
Can you compile libpurple and libdiscord.so with debug symbols and try again?

I'll have a look into the code and see if I can guess where it's dying

**Comment by EionRobb** [comment]
Ok, I'm able to replicate here (with extra debugging) that it segfaults when going offline. :)
Will look into this some more

**Comment by Penaz91** [comment]
Sorry, but I would have needed more guidance on how to compile libdiscord.so with debug symbols, also libpurple should be already compiled with debug symbols (as it's part of portage's Pidgin package) xP
I'll be around in case you need :)

**Comment by EionRobb** [comment]
Can you try that commit to see if it fixes it for you?

**Comment by Penaz91** [comment]
Seems to disconnect gracefully for now. Thank you kindly :+1:

**Comment by EionRobb** [comment]
Yay :)

**Comment by Penaz91** [comment]
I'm putting this here because it's related. Even though the plugin doesn't crash anymore, it disconnects fairly often, and the debug window reports this:
`(11:44:03) discord: got errno 11, read_len 0 from websocket thread
(11:44:03) discord: got errno 11, read_len 0 from websocket thread`

Shall I make a separated Bug?

**Comment by Penaz91** [comment]
@EionRobb Sorry to bring bad news, but this issue is back for vengeance.
This is the crash backtrace, hopefully it's more helpful than the last one.
[pidgin-backtrace.zip](https://github.com/EionRobb/purple-discord/files/1001351/pidgin-backtrace.zip)

**Comment by EionRobb** [comment]
@Penaz91 Can you try that commit?

**Comment by Eloston** [comment]
How do you manage to get unknown users in the buddy list? Do they delete their account or something? Or is there some list of buddies stored locally that has to be synced up with the friends list on Discord?

**Comment by EionRobb** [comment]
@Eloston the new code that @p4plus2 has been working on makes a mirror of the info about users/channels/guilds from the server, but if the server hasn't provided info to us about a user yet, then it would have caused crashing when we try to view info about that user

**Comment by Eloston** [comment]
@EionRobb So where in the code will it re-attempt to get the status and emblem? Do purple clients periodically probe the protocol or something?

**Comment by EionRobb** [comment]
@Eloston correct, every time there's a status change or you click on the buddy or start a conversation window with a buddy it will refresh the emblem/status

**Comment by Penaz91** [comment]
Good Morning, I'm testing the commit now, I will get to you as soon as possible.

**Comment by Penaz91** [comment]
I've been running the plugin for 3 to 4 hours now, plus 1 hour-ish on my university break, no crashes so far. Thank you again for your amazing work
