### ISSUE TITLE
Offline messages not received

### ISSUE THREAD

**Issue by LurkerHub** [EionRobb/purple-discord#351]
The latest Windows nightly DLL is not receiving messages that were sent when the Pidgin discord account was offline.  Whatever caused it needs to be reverted ASAP as it causes messages to be silently lost.

~~I suspect the V9 changes.  Does anyone have a version prior to those changes?~~

**Comment by LurkerHub** [comment]
Reverting to the V6 DLL did not fix it.

**Comment by LurkerHub** [comment]
A little investigation (names and ids changed to protect the innocent):

After sending an offline message and connecting, blist.xml has the following:

```
<contact>
	<buddy account='thelurker@fastmail.fm' proto='prpl-eionrobb-discord'>
		<name>Buddy#0000</name>
		<alias>Buddy</alias>
		<setting name='last_message_id_high' type='int'>200611539</setting>
		<setting name='last_message_id_low' type='int'>794771456</setting>
	</buddy>
</contact>
```
200611539 = 0xBF516D3
794771456 = 0x2F5F4000
0xBF516D32F5F4000 = 861620000000000000

Discord sends the following (excerpt):
```
{
	"t": "READY",
	"s": 1,
	"op": 0,
	"d": {
		"v": 9,
		"users": [
			{
				"username": "Buddy",
				"public_flags": 0,
				"id": "800000000000000000",
				"discriminator": "0000",
				"avatar": null
			}
		],
		"read_state": {
			"version": 166402,
			"partial": false,
			"entries": [
				{
					"mention_count": 0,
					"last_pin_timestamp": "1970-01-01T00:00:00+00:00",
					"last_message_id": "861640000000000000",
					"id": "900000000000000000"
				}
			]
		},
		"private_channels": [
			{
				"type": 1,
				"recipient_ids": [ "800000000000000000" ],
				"last_message_id": "861640000000000000",
				"id": "900000000000000000"
			}
		]
	}
}
```
Since 861640000000000000 > 861620000000000000, Pidgin should request all the missing messages for conversation 900000000000000000 with buddy 800000000000000000.

But it doesn't.

**Comment by LurkerHub** [comment]
Looks like the plugin does not download any history whatsoever.

**Comment by dlmarquis** [comment]
Does this affect guild chats for you as well as buddy chats?

**Comment by alexolog** [comment]
> Does this affect guild chats for you as well as buddy chats?

Pidgin has never retrieved guild chat history for me.

**Comment by dlmarquis** [comment]
> > Does this affect guild chats for you as well as buddy chats?
> 
> Pidgin has never retrieved guild chat history for me.

I've found that auto-joining channels grabs the missed history at startup.

**Comment by LurkerHub** [comment]
Is it possible to make it not depend on auto-joining?

I tend to start closing tabs when they get too numerous, leaving only the ones I am currently interested in open.
It would be best if opening a channel tab will trigger a history pull.

**Comment by EionRobb** [comment]
> Is it possible to make it not depend on auto-joining?
Unfortunately not.  We have to ask each room one by one if they have any messages since a certain timestamp, which can result in thousands of lookups and triggers rate limits (I tried it once.  Oops!).  The server doesn't volunteer that info in the same way that it does for the private DM's.

**Comment by dlmarquis** [comment]
If you set your chats to persistent, you should be able to close them as
you desire

**Comment by LurkerHub** [comment]
> Unfortunately not.  We have to ask each room one by one if they have any messages since a certain timestamp, which can result in thousands of lookups and triggers rate limits (I tried it once.  Oops!).  The server doesn't volunteer that info in the same way that it does for the private DM's.
Why not trigger the history pull when the user manually opens the room's tab/window?  That way only one room is queried.


> If you set your chats to persistent, you should be able to close them as you desire
Can you please explain the difference between "persistent" and "auto join"?

**Comment by dlmarquis** [comment]
> Can you please explain the difference between "persistent" and "auto join"?

Auto-join joins the chat at start-up. You have to join a chat before you can receive any messages from it.

Persistent means that you want to keep receiving messages from the chat after you close the window (You don't un-join the chat when you close the window). Persistent only affects chats that you have already joined.

**Comment by LurkerHub** [comment]
After setting some of my channels as both persistent and auto-join, Pidgin started hanging on startup.  Had to revert it, and still no history download.

See #364
