### ISSUE TITLE
Websocket thread stops very often, leading to disconnection

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#36]
I'm Sorry to get back here so soon.
After connecting, very often, but still rather inconsistently, the plugin will disconnect with a "Lost connection to server" error.

This happens after a GUILD_SYNC frame, in the debug window you can see this message:

`
(14:53:46) discord: Room has '25' Members
(14:51:20) discord: got errno 11, read_len 0 from websocket thread
(14:51:20) discord: got errno 11, read_len 0 from websocket thread
`

Any trial to force a reconnection ends with staying connected for about 2 seconds and then disconnecting.

After a while, the plugin reconnects itself to the server automatically, usually with a successful outcome.

**Comment by Penaz91** [comment]
I haven't had any instance of this since I started using commit 9b42bb6. Keeping an eye on this

**Comment by InfestedHydra** [comment]
Can confirm random disconnect + 2 seconds till disconnect again when attempting to reconnect, then eventually it fixes itself. Downloaded nightly Windows yesterday. Any way I can help debug?

**Comment by Penaz91** [comment]
A good start would be using the `Help -> Debug Window` function and filter for "discord", to see what triggers the disconnections.

**Comment by InfestedHydra** [comment]
May or may not be related, but it did disconnect right after trying to reconnect:
(13:06:54) discord: got errno 11, read_len 0 from websocket thread
(13:06:54) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\discord.png: Failed to open file 'C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\discord.png': No such file or directory

**Comment by Penaz91** [comment]
`(13:06:54) discord: got errno 11, read_len 0 from websocket thread`
This is the same error I get, so it's related for sure
`(13:06:54) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\discord.png: Failed to open file 'C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\16\discord.png': No such file or directory`
This is a GUI error, where it seems that pidgin is not able to load the protocol icon, this shouldn't influence the behaviour and functionality of the plugin.

**Comment by Penaz91** [comment]
I tried filtering the debug logs for the word "socket" and it seems that the socket gets closed just before the error pops up. Attaching the filtered log.
[socket.zip](https://github.com/EionRobb/purple-discord/files/1049561/socket.zip)

**Comment by InfestedHydra** [comment]
Also
(19:39:08) g_log: purple_connection_get_state: assertion `gc != NULL' failed
And
(19:40:23) g_log: purple_conversation_get_chat_data: assertion `conv != NULL' failed

**Comment by bobbybee** [comment]
This issue has not been updated for a while; I have not been able to reproduce this issue. Please reopen if this bug still occurs.
