### ISSUE TITLE
what is a harmony and why do i need to use that instead of this

### ISSUE THREAD

**Issue by EntranceJew** [EionRobb/purple-discord#361]
i thought the point was to make it work on pidgin
`Consider using Harmony first, then retry`

**Comment by EionRobb** [comment]
Harmony used to be a way to login to Discord that worked with the Recapcha system.  Nowadays there's a workaround using browser tokens: https://github.com/EionRobb/purple-discord#bitlbee-and-spectrum2-users

**Comment by alexolog** [comment]
> Nowadays there's a workaround using browser tokens: https://github.com/EionRobb/purple-discord#bitlbee-and-spectrum2-users

I tried it.  Firefox only shows me local storage for discord.com (redirected from discordapp.com), and there is no "token" entry there.

Or rather, it appears on the screen for a split second and disappears again.  Not enough time to copy it.

**Comment by CorporalCrawdad** [comment]
The workaround is for bitlbee and spectrum2 users, does this extension not work for pidgin then?

**Comment by EionRobb** [comment]
Yes, the plugin is for Pidgin, but normally you'd be logging in from the same IP as where you'd have previously logged in using the official client, so wouldn't trip whatever flag they use to make you go through the recaptcha process

**Comment by jakecoble** [comment]
For anybody else unable to find the token, you can use the network tab in the developer tools to grab the token. If you log in from your browser, the token should be in the first network response you get.
