### ISSUE TITLE
Always popping in

### ISSUE THREAD

**Issue by Nikodemsky** [EionRobb/purple-discord#384]
Sincle last version of windows nightly discord messages just keeps popping in on the top of any other apps - by default it should do it only when someone mention you @ in chat, but it does it with every single message, it's really pain to deal with it...

I have tried tinkering with pidgin settings and even with build-it notifications plugin, but it's like discord completely ignores it and does what it want anyway.

I have no such problems with other protocols such as Steam.

Using latest pidgin, latest discord plugin(win nightly), win10x64/21H1.

If i should provide any other info please let me know.

**Comment by szabolcs-szilagyi** [comment]
I'm experiencing the same issue. Interestingly it doesn't happen with DMs but constantly with group chats.

**Comment by kgraefe** [comment]
That might be related to https://github.com/kgraefe/pidgin-hide-chat-on-join/issues/6 :

> Yesterday I was able to reproduce the issue. Apparently @EionRobb calls [purple_conversation_present()](https://github.com/EionRobb/skype4pidgin/blob/67fcefaf669d2d31a33b5d0c09410cf3ab345006/skypeweb/libskypeweb.c#L258) after creating a chat which presents the chat after creating it ([other purples](https://github.com/tieto/pidgin/blob/38a27b520bfa89b12aad8dd8cc2e317f2f6d9973/libpurple/protocols/irc/msgs.c#L944) don't do this).
> 
> Creating a chat implies presenting, so in fact EionRobb's plugins present the chat twice. My plugin blocks just the first attempt.

**Comment by dlmarquis** [comment]
This should be fixed now. The double-present on join should also be resolved.

**Comment by Nikodemsky** [comment]
Unfortunely still same issue - is there a chance that this fix has not been compiled into latest nightly for win?

**Comment by EionRobb** [comment]
@Nikodemsky yup, that would do it!

Sorry about that :(  Just uploaded a new .dll now
