### ISSUE TITLE
Custom emoji showing at far greater size than line height

### ISSUE THREAD

**Issue by pseudomonas** [EionRobb/purple-discord#396]
Custom emoji in the web interface are shown scaled so their height is equal to text height. This would be nice behaviour to have in a pidgin window too. Otherwise each emoji can take up a fair proportion of the window.

**Comment by dlmarquis** [comment]
There's a way to do this in vanilla Pidgin.
In Pidgin preferences, go to the "Conversations" tab. Towards the end of the prefs list, there is one that says "Resize incoming custom smileys". Tick that, then adjust the maximum size to match your line height.

**Comment by pseudomonas** [comment]
Well, that worked. Thank you, @dlmarquis for your pidgin-skillz! I don't think there's anything discord-specific that needs adding, so I'll close this issue.
