### ISSUE TITLE
Is it possible to read and post to Discord from Linux Terminal using this library? If so how?

### ISSUE THREAD

**Issue by bitcoinmeetups** [EionRobb/purple-discord#401]
652837983

Hello,

I'm BM. A very nice and polite guy.

Is it possible to read and post to Discord from Linux Terminal using this library? If so how?

**Comment by EionRobb** [comment]
Sure, you can use a terminal-based libpurple frontend, such as Finch (ncurses-based), or use the DBus API that libpurple ships with to send `purple-remote` commands to a running instance

They're all a bit outside of the scope of this plugin though :)
