### ISSUE TITLE
Can't sign into my discord: Changed password and disabled 2Factor

### ISSUE THREAD

**Issue by serrebi** [EionRobb/purple-discord#406]
Hello: I cannot connect to my account on Ubuntu 22.04 pidgin + purple_discord.
I can use Discord client fine,and can also connect to the web client. Here is the debug log.
(15:18:31) account: Connecting to account brandon@bracey.ca.
(15:18:31) connection: Connecting. gc = 0x562245aa94a0
(15:18:31) signals: Signal data for chat-conversation-typing not found!
(15:18:31) discord: Fetching url https://discord.com/api/v9/auth/login
(15:18:31) discord: With postdata ###PASSWORD REMOVED###
(15:18:31) http: Performing new request 0x562245d32460 to discord.com.
(15:18:31) dnsquery: Performing DNS lookup for discord.com
(15:18:31) dns: Created new DNS child 7877, there are now 1 children.
(15:18:31) dns: Successfully sent DNS request to child 7877
(15:18:31) dns: Got response for 'discord.com'
(15:18:31) dnsquery: IP resolved for discord.com
(15:18:31) proxy: Attempting connection to 162.159.128.233
(15:18:31) proxy: Connecting to discord.com:443 with no proxy
(15:18:31) proxy: Connection in progress
(15:18:31) proxy: Connecting to discord.com:443.
(15:18:31) proxy: Connected to discord.com:443.
(15:18:31) nss: SSL version 3.4 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit TLS 1.3, Key Exchange: 255-bit TLS 1.3, Compression: NULL
Cipher Suite Name: TLS_AES_128_GCM_SHA256
(15:18:31) nss: subject=CN=sni.cloudflaressl.com,O="Cloudflare, Inc.",L=San Francisco,ST=California,C=US issuer=CN=Cloudflare Inc ECC CA-3,O="Cloudflare, Inc.",C=US
(15:18:31) nss: subject=CN=Cloudflare Inc ECC CA-3,O="Cloudflare, Inc.",C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(15:18:31) nss: partial certificate chain
(15:18:31) certificate/x509/tls_cached: Starting verify for discord.com
(15:18:31) certificate/x509/tls_cached: Checking for cached cert...
(15:18:31) certificate/x509/tls_cached: ...Found cached cert
(15:18:31) nss/x509: Loading certificate from /home/serrebi/.purple/certificates/x509/tls_peers/discord.com
(15:18:31) certificate/x509/tls_cached: Peer cert matched cached
(15:18:31) nss/x509: Exporting certificate to /home/serrebi/.purple/certificates/x509/tls_peers/discord.com
(15:18:31) util: Writing file /home/serrebi/.purple/certificates/x509/tls_peers/discord.com
(15:18:31) nss: Trusting CN=sni.cloudflaressl.com,O="Cloudflare, Inc.",L=San Francisco,ST=California,C=US
(15:18:31) certificate: Successfully verified certificate for discord.com
(15:18:32) http: Request 0x562245d32460 performed without success.
(15:18:32) discord: Got response: {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"}
(15:18:32) connection: Connection error on 0x562245aa94a0 (reason: 2 description: Need CAPTCHA to login. Consider using Harmony first, then retry.)
(15:18:32) account: Disconnecting account brandon@bracey.ca (0x5622457e01a0)
(15:18:32) connection: Disconnecting connection 0x562245aa94a0
(15:18:32) connection: Destroying connection 0x562245aa94a0
Hope this helps you find the issue.

**Comment by EionRobb** [comment]
Ah, that's looking for a captcha rather than a 2fa.  Unfortunately recaptcha needs javascript, which Pidgin doesn't support.  You'll need to follow the workaround to get a token from your browser from https://github.com/EionRobb/purple-discord#bitlbee-and-spectrum2-users

**Comment by guglovich** [comment]
@EionRobb Will there be any plans for a GUI for token entry? .xml file is bad at least because of the open storage of authorisation in unencrypted form. And in general the plugin is old and there are no steps towards user friendliness.

**Comment by bodqhrohro** [comment]
> .xml file is bad at least because of the open storage of authorisation in unencrypted form

So you complain about the whole libpurple architecture per just one prpl, huh? C'mon, it's a messenger from 00s.

I rather find this an advantage, and have a butthurt from modern Gajim, as at some point it lost an ability to store passwords itself, so since I disabled gnome-keyring-daemon, I have to type passwords for every account manually on every start. Guess where do I obtain those I don't remember ;D

Paranoid users may isolate the access to application data per application, like it's done on Android, what's the matter to enforce ad-hoc encryption for everyone on application level? If the encrypted data can be accessed by an attacker, the decryption key for them can be accessed too anyway, so it's just a pointless obscurity level.

There is a downside of a plain text XML if compared with binary databases though: it may get corrupted by any plugin if it tries to store non-textual data. I've encountered this when developing a prpl, luckily, I did it on a separate profile.

**Comment by guglovich** [comment]
> > .xml file is bad at least because of the open storage of authorisation in unencrypted form
> 
> So you complain about the whole libpurple architecture per just one prpl, huh? C'mon, it's a messenger from 00s.
> 
> I rather find this an advantage, and have a butthurt from modern Gajim, as at some point it lost an ability to store passwords itself, so since I disabled gnome-keyring-daemon, I have to type passwords for every account manually on every start. Guess where do I obtain those I don't remember ;D
> 
> Paranoid users may isolate the access to application data per application, like it's done on Android, what's the matter to enforce ad-hoc encryption for everyone on application level? If the encrypted data can be accessed by an attacker, the decryption key for them can be accessed too anyway, so it's just a pointless obscurity level.
> 
> There is a downside of a plain text XML if compared with binary databases though: it may get corrupted by any plugin if it tries to store non-textual data. I've encountered this when developing a prpl, luckily, I did it on a separate profile.

There's paranoia, encrypting everything you can and all that, but I'm talking about basic security, it's the basics. You don't even need a hacker to copy a password from an open file, just an average girl or child. So there's just the concept of basic things.
P.S. I'm against gnome-keyring too

**Comment by bodqhrohro** [comment]
> You don't even need a hacker to copy a password from an open file, just an average girl or child

If you allow kids to use a computer with your own account, unencrypted passwords are really not a biggest problem. If they have their own accounts, they just wouldn't have a read access to `accounts.xml`. Those are the basics of multi-user UNIX-like systems.

**Comment by guglovich** [comment]
> > You don't even need a hacker to copy a password from an open file, just an average girl or child
> 
> If you allow kids to use a computer with your own account, unencrypted passwords are really not a biggest problem. If they have their own accounts, they just wouldn't have a read access to `accounts.xml`. Those are the basics of multi-user UNIX-like systems.

This again is a shift to paranoia. You are simply listing ways to reduce the odds yourself, instead of agreeing that there are basics of security, this is shifting responsibility to the user. I'm afraid to imagine what would happen if there were such an attitude towards software everywhere.

**Comment by bodqhrohro** [comment]
> shifting responsibility to the user

This is what free software is about: being controlled by a user rather than by some third parties who think they know better.

**Comment by EionRobb** [comment]
This is all getting rather off topic from the original issue of needing the auth token. Thanks for the discussion
