### ISSUE TITLE
XMPP Discovery in pidgin by using spectrum2 as transport for discord does only show server

### ISSUE THREAD

**Issue by Fank** [EionRobb/purple-discord#43]
If i add the purpe-discord to spectrum2 i only see the servers:

![image](https://cloud.githubusercontent.com/assets/1900106/26642560/775843f8-462e-11e7-9683-b9b06692256b.png)

I know it works fine in pidgin self, without spectrum. Because the channels are 1 level deeper. Is it possible to support spectrum2 so i can see channels too?

-> https://github.com/hanzz/spectrum2
-> https://hub.docker.com/r/fankserver/spectrum2/ (Docker image which contains your lib)

**Comment by EionRobb** [comment]
Hmm... I wonder if it's something that needs to be added to spectrum2 instead?  Have you submitted a corresponding issue there?

**Comment by Fank** [comment]
Not now but will do it later

**Comment by EionRobb** [comment]
It should be possible to add in some detection to know if it's spectrum2 and if so, change the layout of the room list, but it would be really nice if spectrum2 added support for this instead :)

**Comment by Fank** [comment]
I can confirm both, will create issue with this info

**Comment by bobbybee** [comment]
I suspect we are not the only prpl that follows this paradigm. spectrum2 should support this correctly, although it seems you have submitted a patch upstream. I hope it is merged :smile:

Closing

**Comment by thundergreen** [comment]
dumb question: what type do u use in spectrum transport.cfg? @Fank  ?
