### ISSUE TITLE
orphaning Debian package of purple-discord

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#439]
I am soon going to be stopping using purple-discord.
So I will be orphaning the Debian package of it.
If anyone wants to adopt it, I can help you get started, sponsor it etc.
If no-one wants to adopt it, I wonder if I should remove it from Debian?

**Comment by Tirus42** [comment]
Can you shortly explain what are the tasks for a  maintainer of this package?
Is it "just" to provide a actual .deb file build with the current state of the master branch
(which could be done automatically using a build pipeline) or what a the specific tasks?

**Comment by pabs3** [comment]
Building the .deb package distributed by Debian happens automatically
on the Debian auto-build machines (buildds), but the maintainer should
test that it works locally before uploading.

The role of a Debian package maintainer is mostly quality assurance and
co-ordination between users and upstream.

purple-discord usually doesn't get any Debian bug reports though,
unless Discord completely breaks the plugin.

Usually I review all the upstream commits since the last upload to
Debian, update the Debian copyright file if needed, test the package
still builds and I can still login to and use Discord, run some static
analysis tools over the codebase (cppcheck, scan-build, GCC analyzer),
run Debian package static analysis (lintian/duck), check the package
tracker suggestions, report back any issues/patches to upstream and
sign and upload the package. Most uploads take 1 hour maximum though.
Sometimes I'll also go through the bugs/patches from distros other than
Debian (see the "other distros" link on the tracker) and forward
anything of value to upstream. Sometimes if I have time I'll look at
the upstream issues and contribute comments/patches for them. You can
take a look at the commits to this repo for my minor contributions.

https://tracker.debian.org/pkg/purple-discord

Here are the official Debian docs about this process:

https://mentors.debian.net/intro-maintainers/
https://www.debian.org/doc/manuals/maint-guide/update.en.html#inspectnewupstream

In addition I keep up with developments in Debian and think about how
they apply to purple-discord. For example the freeze for bookworm will
be starting soon so I have to think about if purple-discord should be
kept in Debian or removed before the release.

***@***.***

BTW, I am also orphaning the Debian harmony package, which lets you
manage your Discord account, delete it or register an account.

https://github.com/taylordotfish/harmony/issues/19

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I have now orphaned the Debian package of purple-discord:

https://bugs.debian.org/1032178

Please comment here or contact me for help taking it over.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by Nardol** [comment]
@pabs3 By reading what you did for this package maintenance, I think I could take it over with some help from you for the beginning because it would be my first experience in this domain.
I already have built some Debian packages, not from scratch which would not be the case for purple-discord so why not becoming the maintainer for this package I use myself.
To be honest, I also have read Debian documentation where I lost myself :laughing:

Of course, except if someone else has already contacted you privately :slightly_smiling_face:

**Comment by pabs3** [comment]
@Nardol Thanks! There hasn't been anyone else interested in taking over
the Debian package of purple-discord yet, so it is all yours!

Lets discuss further elsewhere, we can discuss in public on the OFTC
IRC network in the #debian-mentors IRC channel or via mail on the
debian-mentors mailing list. If you prefer to discuss in private
then I am pabs on OFTC or you can mail me at ***@***.***

https://oftc.net/
https://wiki.debian.org/IRC
https://lists.debian.org/debian-mentors/

**Comment by pabs3** [comment]
@Nardol has adopted the Debian purple-discord package, I will be sponsoring uploads.
