### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by bobbybee** [EionRobb/purple-discord#44]
At the moment, custom emojis do not display correctly, and custom emojis cannot be sent. I'm currently implementing a patch for these issues. The former is currently done locally; I'm working on the latter at the moment.

Related question: where is the entrypoint for message sending, so I can intercept anything the user sends in between hitting enter and it getting sent to Discord?

**Comment by EionRobb** [comment]
Awesome stuff 👍 

You'll be wanting to look at the `discord_conversation_send_message()` function https://github.com/EionRobb/purple-discord/blob/master/libdiscord.c#L3235-L3264

**Comment by bobbybee** [comment]
Sending emoji now works as well using \:emoji\: syntax. That was a bigger project than anticipated...

I still have some loose ends to tie up (like rendering emojis that *you* send), and I need to normalise the code style, but I should have a patch ready either this evening or tomorrow.

**Comment by bobbybee** [comment]
Subissue I just noticed: Discord users may silently expect the "standard" Unicode emojis to be typed with \:emoji\: syntax. Handling this is significantly more complex, because the names aren't standard. The tables are available as machine-readable JSON [here](https://github.com/Necktrox/discord-emoji); however, bundling this may incur hamper performance and/or size. I'm not sure if this is something I should look into seriously or not -- right now, the bigger issue for emojis in Pidgin appears to be font support...

**Comment by bobbybee** [comment]
I'm heading to sleep. There are some serious formatting issues with the patch and I'm aware of a number of memory leaks (read: not ready to merge!), but you can take a look at my [patch](https://rosenzweig.io/paste_1496299296.patch)

**Comment by EionRobb** [comment]
How does the patch work in with emoji 3rd party smiley themes such as https://github.com/stv0g/unicode-emoji or https://github.com/VxJasonxV/emoji-for-pidgin ?

**Comment by bobbybee** [comment]
See the commit message on the [email-formatted patch](https://rosenzweig.io/0001-Implement-custom-emojis.patch) (ready for review)

**Comment by alexolog** [comment]
Unicode emojis don't seem to display at all for me.  I get tofu instead.

**Comment by Nikodemsky** [comment]
Same issue here, any chance to get it fixed in near future?

**Comment by EionRobb** [comment]
> Same issue here, any chance to get it fixed in near future?

Are you on the latest version?  Custom emoji support has already been added.  If this is about something else, could you open a new issue?

**Comment by Nikodemsky** [comment]
It's the same i think, i'm getting ![emoji](https://i.postimg.cc/NfhdZYkH/emoji.png) instead of actual emoji.

I'm using nightly build for win, should i use something else?

**Comment by joker314** [comment]
Are you typing out the emoji (as in, the character) on your client, or is this about incoming messages?

**Comment by Nikodemsky** [comment]
incoming messages

**Comment by Berndinox** [comment]
2021 still face this issue
sadly this makes pidgin unusable because some chats consist of 50% emoji spams

**Comment by alyssarosenzweig** [comment]
> some chats consist of 50% emoji spams

I am intrigued by what one gets out of such a chat.

**Comment by EionRobb** [comment]
2021 and the plugin still displays emoji with one of the emoji smiley themes https://github.com/niclashoyer/pidgin-emojione https://github.com/stv0g/unicode-emoji or https://github.com/VxJasonxV/emoji-for-pidgin  :)

**Comment by Berndinox** [comment]
Oh…. Thais Great! Thanks for Sharing!
;)

**Comment by EionRobb** [comment]
@dlmarquis that doesn't work on windows, due to winPidgin using a very old version of GTK that doesn't support emoji characters in text
