### ISSUE TITLE
works in BitlBee but changes to 'unknown' in Pidgin.

### ISSUE THREAD

**Issue by dchmelik** [EionRobb/purple-discord#454]
For the last couple commits (earlier this month and a few minutes ago) purple-discord works in BitlBee but my Pidgin account changes from 'discord' to 'unknown'.

**Comment by EionRobb** [comment]
Can you get a debug output? 

Open the debug window, (Help -> Debug Window) then keep that open and open the plugins list (Tools -> Plugins) then close the plugins list and copy the output of the debug window into here?

**Comment by dchmelik** [comment]
gist:[purple-debug.log](http://gist.github.com/dchmelik/27554cbb5fcdad36957e4c0de9e1ec17)

**Comment by EionRobb** [comment]
That's odd. It's showing as loading fine. I'd have expected it to say that it couldn't load because of missing deps or something. Hmm. 

So if you add a new discord account in pidgin, does it not show up in the drop down list of protocols to choose from?

**Comment by dchmelik** [comment]
> So if you add a new discord account in pidgin, does it not show up in the drop down list of protocols to choose from?

Actually, when I did that, it recreated my account and works... I forgot they may have switched from username (in my original account) to email (in recreated account).
