### ISSUE TITLE
its anoying not knowing the name of a server

### ISSUE THREAD

**Issue by Spike1377** [EionRobb/purple-discord#455]
sometimes you get a random dm from a random channel on a random sever. pidgin will say general at the top but that the channel name not the server name

(00:23:54) me: what server is this?
(00:23:59) ┌──@otherotherperson: Even if you manage to do it, it'...
(00:23:59) otherperson: i remember it should have started the game
(00:24:03) me: pidgen is abnoying
(00:24:04) ┌──@me: what server is this?
(00:24:04) otherperson: riiconnect24..?
(00:24:08) me: ok thanks

it would be nice to have it next to the channel name in the pidgin window but I don't think that can work or if it did it would say the server id or something

why isnt there a /name or /servername it would really help, thanks.

**Comment by EionRobb** [comment]
That's a handy idea :) I like it :)

**Comment by Spike1377** [comment]
did you make it yet?

**Comment by EionRobb** [comment]
There ya go :)

There's now a `/servername` command that outputs the name of the server into the chat window

**Comment by Spike1377** [comment]
Thank you.
