### ISSUE TITLE
ERROR: You need libpurple development headers installed to be able to compile this plugin

### ISSUE THREAD

**Issue by axelnieves2012** [EionRobb/purple-discord#457]
How do I install: "libpurple development headers to be able to compile this plugin"??

If i need libpurple development headers installed to be able to compile this plugin, why don't you provide it?

how to download/install libpurple???

**Comment by smeagolthellama** [comment]
https://github.com/EionRobb/purple-discord?tab=readme-ov-file#compiling

Use the package manager your OS comes with to find the libraries listed here, and install them. also, next time, try using a search engine. Just copy-pasting the error message usually works for me, or at least sets me on the right track.
