### ISSUE TITLE
Channels are not persistent anymore

### ISSUE THREAD

**Issue by Eloston** [EionRobb/purple-discord#54]
Whenever I open a channel (whether it be via auto-join or manually opening the chat window) and close it, the history is cleared and the people list are re-loaded the next time I open it again. I also don't get system notifications of direct notifications when the channel window is closed (unlike other Pidgin rooms I have)

This happened around the same time I got #53.

**Comment by Experimenter** [comment]
Also affected by the same bug, despite persistent channels, all the messages that are sent once the chat window is closed are lost. I only receive messages when the channel window/tab remain open.

**Comment by bobbybee** [comment]
Given the new history implementation this should no longer be relevant. Closing
