### ISSUE TITLE
Issues with markdown escapes break emojis, links, etc

### ISSUE THREAD

**Issue by bobbybee** [EionRobb/purple-discord#55]
This regression is the result of the naive markdown escape I implemented. A proper refactor would help tremendously to solve quirks like this.

**Comment by r4m0n** [comment]
Probably related: URLs with '_', '*' or '~' in them get an extra '/' before the characters, breaking links passed to Discord users.

**Comment by bobbybee** [comment]
This is the same bug, yeah.
