### ISSUE TITLE
Direct Messages repeat

### ISSUE THREAD

**Issue by lanirwolfe** [EionRobb/purple-discord#57]
Commit 4c4c480 introduced a change that causes direct messages to be fetched from the discord server multiple times. Looks like a fix would entail either setting those messages as read on the discord server or not refetching them.

**Comment by maxtros** [comment]
confirmed

**Comment by bobbybee** [comment]
Yes, this is a known issue (I didn't implement ack'ing messages yet). That said, replying to message acknowledges it implicitly and stops it from repeating.

**Comment by alexolog** [comment]
This workaround is not a good one since it requires a reply to every message.  How does one end a conversation?

It is quite annoying and a fix will be highly appreciated.

**Comment by EionRobb** [comment]
I wonder if another workaround is to send a typing notification, eg to start typing to someone, then delete that message

**Comment by alexolog** [comment]
Tried that, doesn't seem to work.

**Comment by EionRobb** [comment]
Ugh, that commit didn't help at all.  Will have another go at it.

**Comment by maxtros** [comment]
any news?. Thanks!

**Comment by alexolog** [comment]
Please fix it.  Thank you.

**Comment by alexolog** [comment]
Please reopen, problem still exists.
