### ISSUE TITLE
Support Private Group DMs

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#59]
Private Group DMs used to show in the Room List.  Consider adding them to the buddy list automatically (like buddies are)

**Comment by keiyakins** [comment]
At the very least, not crashing whenever you receive a message in one would be a good thing.

**Comment by EionRobb** [comment]
Can you attach a backtrace of the crash? https://developer.pidgin.im/wiki/GetABacktrace

**Comment by bobbybee** [comment]
:tada:

I'll implement this now.

**Comment by bobbybee** [comment]
Closed by #94
