### ISSUE TITLE
Crashes pidgin when attempting to join channel you don't have permission to access.

### ISSUE THREAD

**Issue by rdvl97** [EionRobb/purple-discord#6]
While you are able to see all the channels on the discord server with this plugin, you have to be granted access to some of them by the admin.  trying to access these channels ends up crashing pidgin

**Comment by EionRobb** [comment]
Can you get a backtrace?  On windows that's in the `%appdata%\.purple\Pidgin.RPT` file

**Comment by rdvl97** [comment]
im running pidgin portable 
and it doesnt seem to access %appdata%
lemme see if i can get it to save it.  if i cant ill load up ollydbg and see if i can get a capture of the debug console when it hangs

**Comment by EionRobb** [comment]
Wherever your .purple folder lives is where the Pidgin.RPT file should be

**Comment by rdvl97** [comment]
for some reason my .purple folder doesnt have the file

**Comment by rdvl97** [comment]
got it to generate the backtrace
is there any sensitive info i need to strip from it?

**Comment by rdvl97** [comment]
nvm, opened it up and its fine  
`-------------------

Error occured on Tuesday, April 18, 2017 at 01:05:45.

Windows Version 6.1 Build 7601 Service Pack 1

F:\PortableApps\PidginPortable\App\Pidgin\pidgin-portable.exe caused an Access Violation at location 68609843 in module F:\PortableApps\PidginPortable\App\Pidgin\Gtk\bin\libglib-2.0-0.dll Reading from location 00000000.

Registers:
eax=00000000 ebx=01f515d0 ecx=00000000 edx=00000000 esi=0000014b edi=0000014b
eip=68609843 esp=0028dca4 ebp=0028dca8 iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246

Call stack:
         F:\PortableApps\PidginPortable\App\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
68609843 F:\PortableApps\PidginPortable\App\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_str_hash
687C6E05 F:\PortableApps\PidginPortable\App\Pidgin\plugins\libdiscord.dll  discord_got_channel_info  C:\cygwin\home\Eion\purple-discord/libdiscord.c:2904
687C19ED F:\PortableApps\PidginPortable\App\Pidgin\plugins\libdiscord.dll  discord_response_callback  C:\cygwin\home\Eion\purple-discord/libdiscord.c:497
         F:\PortableApps\PidginPortable\App\Pidgin\libpurple.dll [2.12.0.0]
5816692B F:\PortableApps\PidginPortable\App\Pidgin\libpurple.dll  purple_util_fetch_url_request





`

**Comment by EionRobb** [comment]
Can you try with the latest dll?

I should add in some checks into the room list as to whether we have permissions to join a room, so they don't display in the list, but that should probably be a different issue.

**Comment by rdvl97** [comment]
they still show up in the list but there's no more crashing :3
