### ISSUE TITLE
Unable to build on FreeBSD - Makefile requires mercurial but clone is not under mercurial repo

### ISSUE THREAD

**Issue by eeboaz** [EionRobb/purple-discord#64]
```
$ gmake
gmake: hg: Command not found
echo "You need libpurple development headers installed to be able to compile this plugin"
You need libpurple development headers installed to be able to compile this plugin
```

I installed mercurial via pkg and ran gmake again:
```
$ gmake
abort: there is no Mercurial repository here (.hg not found)
```

Can I just change these out with the appropriate git calls?

**Comment by EionRobb** [comment]
hg is just optional.  The important part is about needing the libpurple development headers.  What's the output of `pkg-config --libs --cflags purple-2` ?

**Comment by eeboaz** [comment]
I think the verbiage of the mercurial message (abort) was causing me to focus on the wrong issue.

pkg-config (freedesktop.org) isn't available for FreeBSD. I'll add some FreeBSD specific updates to the Makefile (within ifeq blocks) and see if I can get it to build. I'll send a PR once I get it working.


FYI, I do have the libpurple installed - they're in /usr/local/include/libpurple on FreeBSD:

```
$ pkg query %n-%v | grep purple
libpurple-2.12.0_2
```

**Comment by EionRobb** [comment]
what about if you use  `PKG_CONFIG=pkgconf gmake`?

**Comment by eeboaz** [comment]
This definitely helped -- I was going about this the wrong way.  No changes are needed for the current Makefile. I was able to build this for FreeBSD using your suggestions and studying a makefile from another (similar) FreeBSD port to determine what I was missing.

The plugin is working great with Pidgin.  I'll work with one of the FreeBSD ports committers to get this submitted to the FreeBSD ports collection.

Thank you very much for your assistance!

**Comment by bobbybee** [comment]
Closing as the issue seems to be fixed :smile:
