### ISSUE TITLE
Discord Crash under Pidgin,.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/purple-discord#66]
Pidgin started unexpectedly crashing with this error:

Server error: "Client skipped ahead (frame.seq=3, numResent=-2, numAcked=7, clientSeq=1)". If this keeps happening, report a bug. Try to include the debug window messages before the error happens.

**Comment by EionRobb** [comment]
"Client skipped ahead" is a FunYahoo++ error, but is fairly harmless.

If you're getting crashes, please follow https://developer.pidgin.im/wiki/GetABacktrace and attach to this issue

**Comment by Zombie-Ryushu** [comment]
I am, but I wasn't running this from Terminal.

**Comment by bobbybee** [comment]
Stale issue with no backtrace, closing. Please reopen with more information if this is still an issue (it is possible that recent changes have fixed / made it worse)
