### ISSUE TITLE
libdiscord.dll reported as virus/malware

### ISSUE THREAD

**Issue by Sofaspud** [EionRobb/purple-discord#69]
Using the link from the repo, "libdiscord.dll" appears to be flagging as a virus according to Windows Defender.  I am unable to verify if this is a false positive or if the repo has been corrupted.

**Comment by EionRobb** [comment]
Just scanned the dll again, https://www.virustotal.com/en/file/7cba43b9d6fa0cf31e765659cc3a58a3921337ba80c5e93fc216b39d00fca838/analysis/1501305328/ says its ok still.  There's been several false positive reports from Windows Defender lately.  There's a submission process to get the file manually verified that myself and several others have used, but haven't had any reply on yet.

**Comment by Sofaspud** [comment]
I've submitted another false positive report to Microsoft.  Hopefully they'll get it sorted.

**Comment by tofof** [comment]
Windows Defender still has this behavior as of today.

**Comment by Sofaspud** [comment]
Just did my monthly check, I can now install without Defender getting its panties in a bunch about "libdiscord.dll".  It's working as of 2017-10-06.  Thanks!
