### ISSUE TITLE
No protocol icon

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#7]
Probably an oversight

**Comment by EionRobb** [comment]
There are icons in the project that get installed when running `make install` but if you've using the windows dll then you'll need to copy them in manually. 

I'll update the instructions on the readme until there's an installer that can do this automatically

**Comment by alexolog** [comment]
On windows.

Speaking of plugin installers, all the ones that I used install into the program directory, where it gets wiped out when upgrading Pidgin to a new version.  I now back up the old installation then copy back the missing files.

**Comment by EionRobb** [comment]
Ok, so if you copy the discord{16,22,48}.png icons from https://github.com/EionRobb/purple-discord to your C:\Program Files (x86)\Pidgin\pixmaps\pidgin\protocols\{16,22,48} folder then you should see the icons in Pidgin

**Comment by alexolog** [comment]
Thanks!

What about "scalable" icons and emotes?

**Comment by EionRobb** [comment]
"scalable" isn't used by Pidgin.  You'll need a 3rd party smiley theme if you want emotes :)
