### ISSUE TITLE
Windows nightly builds link is broken

### ISSUE THREAD

**Issue by JRichmond27** [EionRobb/purple-discord#71]
Windows nightly builds link in the readme file is broken.

**Comment by EionRobb** [comment]
The network connection to the server decided to drop out about 8 hours ago and should have come back about 1-2 hours ago.

Can you try again and see if it's working?

**Comment by JRichmond27** [comment]
Yep! It worked flawlessly this time. It must have come back up right after I opened this issue. 

Thanks!

**Comment by EionRobb** [comment]
Thanks for coming back to report that it's working ok now :)

I think the link was out for a few hours, but not entirely sure
