### ISSUE TITLE
Cannot save room as a contact

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#8]
I joined a "room" conversation, but I see no option to add the channel as a contact

**Comment by EionRobb** [comment]
There's two options for this, the first is to use the "Add" button from the roomlist window
![image](https://cloud.githubusercontent.com/assets/1063865/25152831/76dbd186-24de-11e7-9c90-b804d5188368.png)


The other option is through the Conversation->Add
![image](https://cloud.githubusercontent.com/assets/1063865/25152904/b901c480-24de-11e7-890a-5a284bb12e29.png)

**Comment by alexolog** [comment]
Thanks!

**Comment by alexolog** [comment]
One more question: can you please explain the "persistent" and "auto join" options?

**Comment by EionRobb** [comment]
"Persistent" means that if you close the window you won't leave the chat. For the Discord plugin this just means that you'll receive messages in the background as you can't ever leave a chat room.

"Auto join" means that it will open the chat window the next time you start Pidgin

**Comment by alexolog** [comment]
Thanks

**Comment by alexolog** [comment]
> as you can't ever leave a chat room.

Can you please elaborate?

**Comment by EionRobb** [comment]
Discord doesn't let you leave/part a room, the closest you can get to it is have a server admin change the permissions of a room so that you can't read it anymore
