### ISSUE TITLE
Can't Compile on Linux Mint 17.3 (Trusty 14.04) - Mercurial hg?

### ISSUE THREAD

**Issue by WithThisHerring** [EionRobb/purple-discord#80]
Following instructions at https://github.com/EionRobb/purple-discord#compiling , I enter
```
$ git clone git://github.com/EionRobb/purple-discord.git
Cloning into 'purple-discord'...
remote: Counting objects: 662, done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 662 (delta 133), reused 179 (delta 98), pack-reused 446
Receiving objects: 100% (662/662), 290.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (417/417), done.
Checking connectivity... done.
$ cd purple-discord
$ make
```
and the following appears:
```
abort: there is no Mercurial repository here (.hg not found)
cc -fPIC -O2 -g -pipe -Wall -std=c99 -DDISCORD_PLUGIN_VERSION='"0.9.2017.08.12"' -shared -o libdiscord.so libdiscord.c -Wl,-z,relro  `pkg-config purple glib-2.0 json-glib-1.0 --libs --cflags`   -Ipurple2compat -g -ggdb
```
Optimistically hoping that error wouldn't matter and I could skip to checkinstall... (Checkinstall per [xvitaly's advice](https://github.com/EionRobb/skype4pidgin/issues/488#issuecomment-254660940) on my question regarding your Skype plugin :)  )
`$ sudo checkinstall` 
With result (super-long, so stuck in pastebin):
https://pastebin.com/ScugQiKB

I have googled the error, but I can't find anything that is relevant to this plugin or my OS (Linux Mint 17.3, based on Ubuntu Trusty 14.04).  Mercurial is installed.  Pidgin 2.10.9 (libpurple 2.10.9) is installed.  I don't think the advice on [this closed issue applies](https://github.com/EionRobb/purple-discord/issues/64), as eeboaz uses very different installation commands, but I could be horribly wrong.  I am still ignorant of too much Linux stuff, so please be very explicit in any help you give me.  Thank you!

**Comment by bobbybee** [comment]
It looks like it did compile?

**Comment by WithThisHerring** [comment]
Some of the last lines from trying checkinstall are
```
Building Debian package... FAILED!
 
*** Failed to build the package
```
so I didn't think so?  Something went wrong...

---> Before I sent this, I went into Pidgin to check, and sure enough, the plugin was in the list!  And upon testing, my buddy list is showing up!  I'm not sure why it has this error and is working, but I am quite happy.  Thank you, bobbybee!

**Comment by bobbybee** [comment]
:tada:
