### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by bobbybee** [EionRobb/purple-discord#95]

**Comment by EionRobb** [comment]
What parts are slow?  Seems fast enough from here

**Comment by bobbybee** [comment]
Dunno. The PR I issued noticeably helped. I'm playing with some more optimisations; we'll see if I can do better.

Mind you, it's not "fast enough from here". I paid good money for this machine. If Pidgin doesn't start instantly, it's not "fast enough". IM clients in the 90s were faster than this.

(/s mostly)

**Comment by bobbybee** [comment]
#96 solved the most egregious issues, closing
